# Stage 1

In [2]:
import os
import pandas as pd

file_path = "/content/cchs_escc_bsw.csv"

print("File exists:", os.path.exists(file_path))

if os.path.exists(file_path):
    print("File size:", round(os.path.getsize(file_path) / (1024**3), 2), "GB")

    # Read only the header first — this does NOT load the full dataset
    df_preview = pd.read_csv(file_path, nrows=5)

    print("Number of columns:", len(df_preview.columns))
    print("\nFirst few column names:")
    print(df_preview.columns.tolist()[:30])

    print("\nFirst 5 rows:")
    display(df_preview)
else:
    print("File not found at:", file_path)

File exists: False
File not found at: /content/cchs_escc_bsw.csv


In [ ]:
# Look at the columns in manageable groups

columns = df_preview.columns.tolist()

print("Total columns:", len(columns))

for start in range(0, len(columns), 100):
    end = min(start + 100, len(columns))
    print(f"\n--- Columns {start + 1} to {end} ---")
    print(columns[start:end])

Total columns: 1002

--- Columns 1 to 100 ---
['ADM_RNO', 'FWGT', 'BSW1', 'BSW2', 'BSW3', 'BSW4', 'BSW5', 'BSW6', 'BSW7', 'BSW8', 'BSW9', 'BSW10', 'BSW11', 'BSW12', 'BSW13', 'BSW14', 'BSW15', 'BSW16', 'BSW17', 'BSW18', 'BSW19', 'BSW20', 'BSW21', 'BSW22', 'BSW23', 'BSW24', 'BSW25', 'BSW26', 'BSW27', 'BSW28', 'BSW29', 'BSW30', 'BSW31', 'BSW32', 'BSW33', 'BSW34', 'BSW35', 'BSW36', 'BSW37', 'BSW38', 'BSW39', 'BSW40', 'BSW41', 'BSW42', 'BSW43', 'BSW44', 'BSW45', 'BSW46', 'BSW47', 'BSW48', 'BSW49', 'BSW50', 'BSW51', 'BSW52', 'BSW53', 'BSW54', 'BSW55', 'BSW56', 'BSW57', 'BSW58', 'BSW59', 'BSW60', 'BSW61', 'BSW62', 'BSW63', 'BSW64', 'BSW65', 'BSW66', 'BSW67', 'BSW68', 'BSW69', 'BSW70', 'BSW71', 'BSW72', 'BSW73', 'BSW74', 'BSW75', 'BSW76', 'BSW77', 'BSW78', 'BSW79', 'BSW80', 'BSW81', 'BSW82', 'BSW83', 'BSW84', 'BSW85', 'BSW86', 'BSW87', 'BSW88', 'BSW89', 'BSW90', 'BSW91', 'BSW92', 'BSW93', 'BSW94', 'BSW95', 'BSW96', 'BSW97', 'BSW98']

--- Columns 101 to 200 ---
['BSW99', 'BSW100', 'BSW101', 'BS

In [ ]:
import os

files = os.listdir("/content")

print("Files currently in Colab:")
for f in files:
    print(f)

Files currently in Colab:
.config
cchs_escc_bsw.csv
sample_data


In [ ]:
import os

print("Files currently in Colab:\n")

for f in os.listdir("/content"):
    if f.endswith(".csv"):
        size_gb = os.path.getsize("/content/" + f) / (1024**3)
        print(f"{f}  →  {size_gb:.2f} GB")

Files currently in Colab:

pumf_cchs.csv  →  0.04 GB
cchs_escc_bsw.csv  →  0.43 GB


In [4]:
import pandas as pd

file_path = "/content/pumf_cchs.csv"

# Read only the header
df_preview = pd.read_csv(file_path, nrows=5)

print("Number of columns:", len(df_preview.columns))

print("\nFirst 50 columns:")
for i, col in enumerate(df_preview.columns[:50], start=1):
    print(f"{i}. {col}")

Number of columns: 255

First 50 columns:
1. VERDATE
2. REFPER
3. ADM_RNO
4. COLMODE
5. COLMODEY
6. COLMODEP
7. GEOGPRV
8. GEODGHR4
9. DHHDGHSZ
10. EDDVH3
11. DHHGAGE
12. DHH_SEX
13. DOMAC
14. MAC_05
15. DOGEN
16. GEN_01
17. GEN_05
18. GEN_10
19. GEN_15
20. GEN_20
21. DOLSM
22. LSM_01
23. LSMDVSWL
24. DOHWT
25. HWTDGISW
26. HWTDGWHO
27. HWTDGBCC
28. DOWTP
29. WTP_50
30. DOCOV2
31. COV2_005
32. COV2_10A
33. COV2_10B
34. COV2_10C
35. COV2_10D
36. COV2_10E
37. COV2_10F
38. COV2_10G
39. COV2_10H
40. COV2_10I
41. COV2_10J
42. COV2_038
43. COV2_030
44. COV2_035
45. COV2_041
46. COV2_45A
47. COV2_45B
48. COV2_45C
49. COV2_45D
50. COV2_45E


In [ ]:
# Identify the module prefix for each variable

columns = df_preview.columns.tolist()

module_prefixes = {}

for col in columns:
    prefix = col[:3]
    module_prefixes[prefix] = module_prefixes.get(prefix, 0) + 1

print("Number of distinct 3-character module prefixes:", len(module_prefixes))

print("\nVariables grouped by module prefix:")
for prefix, count in module_prefixes.items():
    print(f"{prefix}: {count} variable(s)")

Number of distinct 3-character module prefixes: 53

Variables grouped by module prefix:
VER: 1 variable(s)
REF: 1 variable(s)
ADM: 1 variable(s)
COL: 3 variable(s)
GEO: 2 variable(s)
DHH: 3 variable(s)
EDD: 1 variable(s)
DOM: 1 variable(s)
MAC: 1 variable(s)
DOG: 1 variable(s)
GEN: 5 variable(s)
DOL: 3 variable(s)
LSM: 2 variable(s)
DOH: 1 variable(s)
HWT: 3 variable(s)
DOW: 2 variable(s)
WTP: 1 variable(s)
DOC: 6 variable(s)
COV: 26 variable(s)
CCC: 7 variable(s)
CC1: 4 variable(s)
WDM: 1 variable(s)
DOO: 2 variable(s)
OHM: 16 variable(s)
DOE: 3 variable(s)
EAH: 16 variable(s)
DOP: 2 variable(s)
PAA: 41 variable(s)
DOU: 1 variable(s)
UPE: 18 variable(s)
DOS: 3 variable(s)
SBE: 2 variable(s)
SLP: 4 variable(s)
CSS: 6 variable(s)
SPU: 2 variable(s)
SMK: 3 variable(s)
ECV: 9 variable(s)
DOA: 1 variable(s)
ALC: 5 variable(s)
CAN: 12 variable(s)
DOF: 2 variable(s)
FLU: 9 variable(s)
DOR: 1 variable(s)
RHC: 1 variable(s)
LBF: 3 variable(s)
SDC: 3 variable(s)
DOI: 2 variable(s)
INL: 1 variab

the dataset contains a fairly broad collection of health, lifestyle, demographic, socioeconomic, and administrative modules. For example, PAA alone has 41 variables, while COV has 26 and EAH/OHM each contain substantial blocks. The official grouped-variable document confirms that prefixes correspond to real CCHS subject modules; for example, DHH covers dwelling/household variables, FSC food security, GEO geography, HWT height/weight, INC income, LBF labour force, LSM life satisfaction, and PAA physical activity.

53 prefixes does not mean 53 independent feature families we should simply feed into a model. Some prefixes are DO... variables that act as module/inclusion flags, some are administrative, some are derived/grouped variables, and some are actual questionnaire responses. The official naming convention explicitly distinguishes those types.

In [ ]:
# Show the actual variables belonging to each module/prefix

from collections import defaultdict

module_variables = defaultdict(list)

for col in columns:
    module_variables[col[:3]].append(col)

for prefix, vars_in_module in module_variables.items():
    print(f"\n{'='*60}")
    print(f"{prefix}  →  {len(vars_in_module)} variable(s)")
    print(f"{'='*60}")
    print(", ".join(vars_in_module))


VER  →  1 variable(s)
VERDATE

REF  →  1 variable(s)
REFPER

ADM  →  1 variable(s)
ADM_RNO

COL  →  3 variable(s)
COLMODE, COLMODEY, COLMODEP

GEO  →  2 variable(s)
GEOGPRV, GEODGHR4

DHH  →  3 variable(s)
DHHDGHSZ, DHHGAGE, DHH_SEX

EDD  →  1 variable(s)
EDDVH3

DOM  →  1 variable(s)
DOMAC

MAC  →  1 variable(s)
MAC_05

DOG  →  1 variable(s)
DOGEN

GEN  →  5 variable(s)
GEN_01, GEN_05, GEN_10, GEN_15, GEN_20

DOL  →  3 variable(s)
DOLSM, DOLMAM, DOLAN

LSM  →  2 variable(s)
LSM_01, LSMDVSWL

DOH  →  1 variable(s)
DOHWT

HWT  →  3 variable(s)
HWTDGISW, HWTDGWHO, HWTDGBCC

DOW  →  2 variable(s)
DOWTP, DOWDM

WTP  →  1 variable(s)
WTP_50

DOC  →  6 variable(s)
DOCOV2, DOCOV3, DOCCC, DOCC1, DOCSS, DOCAN

COV  →  26 variable(s)
COV2_005, COV2_10A, COV2_10B, COV2_10C, COV2_10D, COV2_10E, COV2_10F, COV2_10G, COV2_10H, COV2_10I, COV2_10J, COV2_038, COV2_030, COV2_035, COV2_041, COV2_45A, COV2_45B, COV2_45C, COV2_45D, COV2_45E, COV2_45F, COV2_45G, COV2_45H, COV2_45I, COV2_040, COV3_005

CCC  

In [ ]:
# Create a structural inventory of the PUMF variables

variable_inventory = []

for col in columns:
    prefix = col[:3]

    # Fourth character indicates variable type for standard CCHS names
    if len(col) >= 4:
        var_type_code = col[3]
    else:
        var_type_code = ""

    type_meaning = {
        "_": "Collected",
        "C": "Coded",
        "D": "Derived",
        "F": "Flag",
        "G": "Grouped"
    }.get(var_type_code, "Other / special")

    variable_inventory.append({
        "Variable": col,
        "Module": prefix,
        "Type_Code": var_type_code,
        "Type": type_meaning
    })

variable_inventory = pd.DataFrame(variable_inventory)

display(variable_inventory)

,Variable,Module,Type_Code,Type
0,VERDATE,VER,D,Derived
1,REFPER,REF,P,Other / special
2,ADM_RNO,ADM,_,Collected
3,COLMODE,COL,M,Other / special
4,COLMODEY,COL,M,Other / special
...,...,...,...,...
250,INCDGHH,INC,D,Derived
251,INCDGRCA,INC,D,Derived
252,INCDGRPR,INC,D,Derived
253,INCDGRRS,INC,D,Derived


In [ ]:
# Summarise the PUMF at the module level

module_summary = (
    variable_inventory
    .groupby("Module")
    .agg(
        Number_of_Variables=("Variable", "count")
    )
    .reset_index()
    .sort_values("Number_of_Variables", ascending=False)
)

display(module_summary)

,Module,Number_of_Variables
39,PAA,41
6,COV,26
48,UPE,18
38,OHM,16
24,EAH,16
2,CAN,12
27,FLU,9
25,ECV,9
4,CCC,7
7,CSS,6


## CCHS PUMF Exploration — Stage 1: Dataset Structure

## What I established

The 2022 CCHS Public Use Microdata File (`pumf_cchs.csv`) contains:

- 67,079 respondents
- 255 variables
- 53 distinct module prefixes

The variables cover different CCHS subject areas rather than forming a ready-made set of independent machine-learning features. Major areas include demographics, education, geography, income, chronic conditions, BMI, physical activity, eating habits, smoking/vaping, alcohol use, food security, and other health-related topics.

The CCHS variable naming convention also distinguishes between collected, coded, derived, flagged, and grouped variables. Because the column name alone does not provide enough information to determine whether a variable is appropriate for modelling, the official CCHS documentation will be used when interpreting candidate variables.

The original diabetes model used 11 predictors. This broader exploration is intended to determine what additional information is available and which variables can reasonably be considered in later feature-selection experiments.

At this stage, no features have been selected or removed from the broader dataset.

# Stage 2

In [ ]:
# Broad conceptual grouping of CCHS modules
# This is an exploration map, not a feature-selection decision.

module_groups = {
    "Administrative / Survey structure": [
        "VER", "REF", "ADM", "COL", "DOO", "DOE", "DOP", "DOH",
        "DOW", "DOC", "DOA", "DOF", "DOR", "DOI", "DOG", "DOM"
    ],

    "Demographic / Geographic / Socioeconomic": [
        "GEO", "DHH", "EDD", "MAC", "LBF", "INC"
    ],

    "General health / Chronic conditions": [
        "GEN", "LSM", "CCC", "CC1", "HWT", "WDM", "RHC"
    ],

    "Health behaviours / Lifestyle": [
        "PAA", "EAH", "CSS", "SPU", "SMK", "ECV", "ALC", "SLP"
    ],

    "Health / Medical / Preventive": [
        "OHM", "UPE", "CAN", "FLU", "PCN", "FSC"
    ],

    "Other / Specialized": [
        "SBE", "INL", "INP", "WTP", "WTS", "COV"
    ]
}

# Check that every module has been assigned exactly once
all_grouped_modules = [
    module
    for group in module_groups.values()
    for module in group
]

print("Number of dataset modules:", len(module_order))
print("Number of assigned modules:", len(all_grouped_modules))
print("Unique assigned modules:", len(set(all_grouped_modules)))

missing = [m for m in module_order if m not in all_grouped_modules]
duplicates = [m for m in set(all_grouped_modules) if all_grouped_modules.count(m) > 1]

print("\nModules not assigned:", missing)
print("Modules assigned more than once:", duplicates)

# Create the summary table
rows = []

for group_name, modules in module_groups.items():
    total_variables = sum(
        module_summary.loc[
            module_summary["Module"] == module,
            "Number_of_Variables"
        ].iloc[0]
        for module in modules
    )

    rows.append({
        "Domain": group_name,
        "Modules": ", ".join(modules),
        "Number_of_Variables": total_variables
    })

domain_summary = pd.DataFrame(rows)

display(domain_summary)

Number of dataset modules: 255
Number of assigned modules: 49
Unique assigned modules: 49

Modules not assigned: ['VERDATE', 'REFPER', 'ADM_RNO', 'COLMODE', 'COLMODEY', 'COLMODEP', 'GEOGPRV', 'GEODGHR4', 'DHHDGHSZ', 'EDDVH3', 'DHHGAGE', 'DHH_SEX', 'DOMAC', 'MAC_05', 'DOGEN', 'GEN_01', 'GEN_05', 'GEN_10', 'GEN_15', 'GEN_20', 'DOLSM', 'LSM_01', 'LSMDVSWL', 'DOHWT', 'HWTDGISW', 'HWTDGWHO', 'HWTDGBCC', 'DOWTP', 'WTP_50', 'DOCOV2', 'COV2_005', 'COV2_10A', 'COV2_10B', 'COV2_10C', 'COV2_10D', 'COV2_10E', 'COV2_10F', 'COV2_10G', 'COV2_10H', 'COV2_10I', 'COV2_10J', 'COV2_038', 'COV2_030', 'COV2_035', 'COV2_041', 'COV2_45A', 'COV2_45B', 'COV2_45C', 'COV2_45D', 'COV2_45E', 'COV2_45F', 'COV2_45G', 'COV2_45H', 'COV2_45I', 'COV2_040', 'DOCOV3', 'COV3_005', 'DOCCC', 'CCC_05', 'CCC_80', 'CCC_85', 'CCC_90', 'CCC_135', 'CCCDGSKL', 'CCCDGCAR', 'DOCC1', 'CC1_140', 'CC1_145', 'CC1_155', 'CC1_170', 'DOWDM', 'WDMDGDIF', 'DOOHM', 'OHM_05', 'OHM_15', 'DOOHM3', 'OHM3_05', 'OHM3_10', 'OHM3_15', 'OHM3_18', 'OHM3_

,Domain,Modules,Number_of_Variables
0,Administrative / Survey structure,"VER, REF, ADM, COL, DOO, DOE, DOP, DOH, DOW, D...",30
1,Demographic / Geographic / Socioeconomic,"GEO, DHH, EDD, MAC, LBF, INC",14
2,General health / Chronic conditions,"GEN, LSM, CCC, CC1, HWT, WDM, RHC",23
3,Health behaviours / Lifestyle,"PAA, EAH, CSS, SPU, SMK, ECV, ALC, SLP",86
4,Health / Medical / Preventive,"OHM, UPE, CAN, FLU, PCN, FSC",60
5,Other / Specialized,"SBE, INL, INP, WTP, WTS, COV",32


In [ ]:
# Correct module order: use the Module column from our inventory

module_order = list(dict.fromkeys(variable_inventory["Module"]))

print("Number of distinct CCHS modules:", len(module_order))

print("\nCCHS modules in dataset order:\n")

for i, module in enumerate(module_order, start=1):
    count = (
        variable_inventory["Module"]
        .value_counts()
        .loc[module]
    )

    print(f"{i:2}. {module:4} — {count} variable(s)")

Number of distinct CCHS modules: 53

CCHS modules in dataset order:

 1. VER  — 1 variable(s)
 2. REF  — 1 variable(s)
 3. ADM  — 1 variable(s)
 4. COL  — 3 variable(s)
 5. GEO  — 2 variable(s)
 6. DHH  — 3 variable(s)
 7. EDD  — 1 variable(s)
 8. DOM  — 1 variable(s)
 9. MAC  — 1 variable(s)
10. DOG  — 1 variable(s)
11. GEN  — 5 variable(s)
12. DOL  — 3 variable(s)
13. LSM  — 2 variable(s)
14. DOH  — 1 variable(s)
15. HWT  — 3 variable(s)
16. DOW  — 2 variable(s)
17. WTP  — 1 variable(s)
18. DOC  — 6 variable(s)
19. COV  — 26 variable(s)
20. CCC  — 7 variable(s)
21. CC1  — 4 variable(s)
22. WDM  — 1 variable(s)
23. DOO  — 2 variable(s)
24. OHM  — 16 variable(s)
25. DOE  — 3 variable(s)
26. EAH  — 16 variable(s)
27. DOP  — 2 variable(s)
28. PAA  — 41 variable(s)
29. DOU  — 1 variable(s)
30. UPE  — 18 variable(s)
31. DOS  — 3 variable(s)
32. SBE  — 2 variable(s)
33. SLP  — 4 variable(s)
34. CSS  — 6 variable(s)
35. SPU  — 2 variable(s)
36. SMK  — 3 variable(s)
37. ECV  — 9 variable(s)
3

In [ ]:
# Create a clean module-level inventory in dataset order

module_inventory = (
    variable_inventory
    .groupby("Module", sort=False)
    .agg(
        Number_of_Variables=("Variable", "count"),
        Variables=("Variable", lambda x: ", ".join(x))
    )
    .reset_index()
)

display(module_inventory)

,Module,Number_of_Variables,Variables
0,VER,1,VERDATE
1,REF,1,REFPER
2,ADM,1,ADM_RNO
3,COL,3,"COLMODE, COLMODEY, COLMODEP"
4,GEO,2,"GEOGPRV, GEODGHR4"
5,DHH,3,"DHHDGHSZ, DHHGAGE, DHH_SEX"
6,EDD,1,EDDVH3
7,DOM,1,DOMAC
8,MAC,1,MAC_05
9,DOG,1,DOGEN


In [ ]:
# Load the complete CCHS PUMF

file_path = "/content/pumf_cchs.csv"

df = pd.read_csv(file_path)

print("Dataset loaded successfully.")
print("Shape:", df.shape)

print("\nRows:", df.shape[0])
print("Columns:", df.shape[1])

Dataset loaded successfully.
Shape: (67079, 255)

Rows: 67079
Columns: 255


In [ ]:
# First look at how much data is missing in each variable

missing_summary = pd.DataFrame({
    "Variable": df.columns,
    "Missing_Count": df.isna().sum(),
    "Missing_Percent": (df.isna().mean() * 100).round(2)
})

missing_summary = missing_summary.sort_values(
    "Missing_Percent",
    ascending=False
)

display(missing_summary.head(30))

,Variable,Missing_Count,Missing_Percent
VERDATE,VERDATE,0,0.0
REFPER,REFPER,0,0.0
ADM_RNO,ADM_RNO,0,0.0
COLMODE,COLMODE,0,0.0
COLMODEY,COLMODEY,0,0.0
COLMODEP,COLMODEP,0,0.0
GEOGPRV,GEOGPRV,0,0.0
GEODGHR4,GEODGHR4,0,0.0
DHHDGHSZ,DHHDGHSZ,0,0.0
EDDVH3,EDDVH3,0,0.0


In [ ]:
# Inspect how each PUMF variable is stored

dtype_summary = pd.DataFrame({
    "Variable": df.columns,
    "Data_Type": df.dtypes.astype(str).values,
    "Unique_Values": df.nunique(dropna=False).values
})

display(
    dtype_summary
    .sort_values("Unique_Values")
)

,Variable,Data_Type,Unique_Values
0,VERDATE,int64,1
1,REFPER,object,1
12,DOMAC,int64,1
14,DOGEN,int64,1
27,DOWTP,int64,1
...,...,...,...
105,EAHDVFVT,float64,125
143,PAADVMVA,int64,207
147,PAADVVOL,int64,235
254,WTS_M,float64,45369


### What I just learned

Almost all variables are stored as `int64`, with a smaller number as `float64`, and `REFPER` as text.

More importantly, the **number of unique values varies enormously**:

* Some variables have only **1 unique value**. These are largely the module/control variables such as `DOMAC`, `DOGEN`, `DOHWT`, `DOCCC`, etc. They aren't necessarily “features”; many are telling us whether a module applies or are simply fixed in this particular PUMF.
* Many health/behaviour variables have only **3–8 unique values**, which is what we'd expect from categorical survey responses.
* Some variables have dozens or hundreds of possible values.
* `ADM_RNO` has **67,079 unique values**, which makes sense for a respondent record number.
* `WTS_M` has **45,369 unique values**, which is the survey sampling weight. The official guide identifies `WTS_M` as the sampling weight used for population-level statistical estimates, so we should not treat it as an ordinary predictor.

There is also a subtle but important issue here: **we still haven't identified what the numerical codes mean.** For example, a variable with three unique values might represent Yes/No/Not stated, or something completely different. We cannot infer that from the number of categories alone.


In [ ]:
# Inspect actual values for low-cardinality variables

low_cardinality = dtype_summary[
    (dtype_summary["Unique_Values"] >= 1) &
    (dtype_summary["Unique_Values"] <= 6)
]["Variable"].tolist()

print("Number of variables with 1–6 unique values:", len(low_cardinality))

for col in low_cardinality[:30]:
    print(f"\n{'='*60}")
    print(f"{col}")
    print(df[col].value_counts(dropna=False).sort_index())

Number of variables with 1–6 unique values: 204

VERDATE
VERDATE
20250612    67079
Name: count, dtype: int64

REFPER
REFPER
202201-202210    67079
Name: count, dtype: int64

COLMODE
COLMODE
1    31505
2    30869
3      944
6     3761
Name: count, dtype: int64

COLMODEY
COLMODEY
1     2050
2     1711
6    63318
Name: count, dtype: int64

COLMODEP
COLMODEP
1     2371
2     1283
6    63318
9      107
Name: count, dtype: int64

DHHDGHSZ
DHHDGHSZ
1    24957
2    41625
9      497
Name: count, dtype: int64

EDDVH3
EDDVH3
1     4736
2    11905
3    48112
9     2326
Name: count, dtype: int64

DHHGAGE
DHHGAGE
1     3761
2    10123
3    12829
4    16399
5    23967
Name: count, dtype: int64

DHH_SEX
DHH_SEX
1    31105
2    35974
Name: count, dtype: int64

DOMAC
DOMAC
1    67079
Name: count, dtype: int64

MAC_05
MAC_05
1    29532
2     9485
6    27728
9      334
Name: count, dtype: int64

DOGEN
DOGEN
1    67079
Name: count, dtype: int64

GEN_01
GEN_01
1    11376
2    22925
3    22082
4     8006
5  

## CCHS PUMF Exploration — Stage 2: Initial Data Quality and Coding Inspection

After loading the complete 2022 CCHS PUMF, I checked its basic structure, missing values, data types, and variable cardinality.

The dataset contains:

- **67,079 respondents**
- **255 variables**

The initial check found **0 literal `NaN` values** in the dataset. This does not imply complete information because CCHS uses coded values for valid skips, non-applicable questions, and non-response.

The variables are mainly stored as integer-coded values, with some continuous variables stored as `float64` and `REFPER` stored as text. The number of unique values varies widely across variables.

Two variables were identified as non-predictive from their roles in the PUMF:

- `ADM_RNO` — respondent record identifier
- `WTS_M` — CCHS sampling weight

Both will be excluded from the candidate predictor pool, but the survey weight will be considered separately when documenting the survey methodology.

The main finding from this initial inspection is that CCHS coding must be interpreted using the official documentation rather than by treating numerical codes as universally meaningful.

The next stage therefore examines the special codes and their variable-specific meanings.

# Stage 3

In [ ]:
# Count common CCHS special-code values across all variables

special_code_summary = pd.DataFrame({
    "Variable": df.columns,
    "Code_6_Count": [(df[col] == 6).sum() for col in df.columns],
    "Code_9_Count": [(df[col] == 9).sum() for col in df.columns]
})

special_code_summary["Code_6_Percent"] = (
    special_code_summary["Code_6_Count"] / len(df) * 100
).round(2)

special_code_summary["Code_9_Percent"] = (
    special_code_summary["Code_9_Count"] / len(df) * 100
).round(2)

display(
    special_code_summary.sort_values(
        "Code_9_Percent",
        ascending=False
    ).head(30)
)

,Variable,Code_6_Count,Code_9_Count,Code_6_Percent,Code_9_Percent
21,LSM_01,5265,9867,7.85,14.71
253,INCDGRRS,0,8830,0.00,13.16
198,ECV2_10,59261,3624,88.35,5.40
24,HWTDGISW,3793,2836,5.65,4.23
26,HWTDGBCC,4213,2816,6.28,4.20
193,ECVDVSMK,0,2790,0.00,4.16
87,OHM3G50A,27341,2662,40.76,3.97
89,OHM3_50E,27341,2662,40.76,3.97
88,OHM3_50C,27341,2662,40.76,3.97
197,ECV2G05C,62771,2641,93.58,3.94


## CCHS PUMF Exploration — Stage 3: Special Codes and Survey Missingness

## What I investigated

I examined the frequency of commonly occurring coded values, particularly `6` and `9`, across the CCHS PUMF.

This was done after finding that the dataset contains no literal `NaN` values.

## Important finding

The absence of `NaN` values does NOT mean that all variables contain complete respondent information.

The CCHS PUMF uses coded response values for different situations, including:

- valid responses,
- valid skips / not-applicable cases,
- and "Not stated" responses.

The meaning of a numerical code is **variable-specific** and therefore cannot be interpreted globally.

For example:

- `ECV2_10` contains a very large number of code `6` values. The official CCHS data dictionary identifies these as **Valid skip**, because the question applies only to a specific subset of respondents.
- `LSM_01` contains many respondents with code `09`, but `09` is a legitimate answer on its 0–10 life-satisfaction scale. The "Not stated" value for this variable is `99`.
- `INCDGRRS` contains code `9` values that are explicitly identified as **Not stated**.

Therefore, a global transformation such as "replace every 6 or 9 with missing" would be incorrect.

## Methodological implication

Before preparing variables for machine learning, special codes must be interpreted using the official CCHS documentation and the universe of each variable.

This means that apparent missingness has to be distinguished into at least:

1. Valid response
2. Valid skip / not applicable
3. Not stated / non-response
4. Other variable-specific special codes

## Current project status

I have not yet changed or cleaned any of these coded values.

I am keeping the original PUMF intact while investigating how its coding works.

## What comes next

The next step is to move from individual code examples to a systematic view of the **coverage and applicability of the different modules**.

The goal is to understand which information is available for most respondents and which information is only available for specific subgroups.

This will help determine which parts of the CCHS could realistically form a broader feature set for later experiments.

# Stage 4

In [ ]:
# Identify CCHS module inclusion/control variables

do_columns = [col for col in df.columns if col.startswith("DO")]

print("Number of DO/control variables:", len(do_columns))
print("\nDO/control variables:")

for col in do_columns:
    print(f"\n{col}")
    print(df[col].value_counts(dropna=False).sort_index())

Number of DO/control variables: 31

DO/control variables:

DOMAC
DOMAC
1    67079
Name: count, dtype: int64

DOGEN
DOGEN
1    67079
Name: count, dtype: int64

DOLSM
DOLSM
1    67079
Name: count, dtype: int64

DOHWT
DOHWT
1    67079
Name: count, dtype: int64

DOWTP
DOWTP
1    67079
Name: count, dtype: int64

DOCOV2
DOCOV2
1    67079
Name: count, dtype: int64

DOCOV3
DOCOV3
1    67079
Name: count, dtype: int64

DOCCC
DOCCC
1    67079
Name: count, dtype: int64

DOCC1
DOCC1
1    67079
Name: count, dtype: int64

DOWDM
DOWDM
0     1949
1    65130
Name: count, dtype: int64

DOOHM
DOOHM
0     1949
1    65130
Name: count, dtype: int64

DOOHM3
DOOHM3
0     1949
1    65130
Name: count, dtype: int64

DOEAH
DOEAH
0    65130
1     1949
Name: count, dtype: int64

DOPAA
DOPAA
0    65130
1     1949
Name: count, dtype: int64

DOUPE
DOUPE
0     1949
1    65130
Name: count, dtype: int64

DOSBE
DOSBE
0    65130
1     1949
Name: count, dtype: int64

DOSLP
DOSLP
0    65130
1     1949
Name: count, dtype: int6

In [ ]:
# Check whether the 1,949 respondents with restricted module availability
# correspond to the three territories grouped under GEOGPRV = 60.

territory_check = {}

for col in do_columns:
    zero_mask = df[col] == 0

    if zero_mask.any():
        territory_check[col] = {
            "DO_0_Count": zero_mask.sum(),
            "DO_0_in_GEOGPRV_60": ((zero_mask) & (df["GEOGPRV"] == 60)).sum(),
            "DO_0_outside_GEOGPRV_60": ((zero_mask) & (df["GEOGPRV"] != 60)).sum()
        }

territory_check_df = pd.DataFrame(territory_check).T

display(territory_check_df)

,DO_0_Count,DO_0_in_GEOGPRV_60,DO_0_outside_GEOGPRV_60
DOWDM,1949,1949,0
DOOHM,1949,1949,0
DOOHM3,1949,1949,0
DOEAH,65130,0,65130
DOPAA,65130,0,65130
DOUPE,1949,1949,0
DOSBE,65130,0,65130
DOSLP,65130,0,65130
DOFLU,1949,1949,0
DOINL,1949,1949,0


## CCHS PUMF Exploration — Stage 4: Module Applicability and Geographic Structure

## What I investigated

I identified the CCHS `DO...` variables, which act as module inclusion or applicability indicators, and examined their respondent-level values.

There are **31 DO/control variables** in the PUMF.

Many modules have an inclusion value of `1` for all 67,079 respondents. However, several modules have values that differ between respondents.

## Hypothesis tested

I observed that several module flags had exactly **1,949 respondents** with a different inclusion value.

The official CCHS documentation identifies 1,949 respondents as the grouped Yukon / Northwest Territories / Nunavut category (`GEOGPRV = 60`).

I therefore tested whether the unusual module availability was explained by this geographic grouping.

## Result

For the following modules, all respondents with the module flag equal to 0 were exactly the respondents with `GEOGPRV = 60`:

- DOWDM
- DOOHM
- DOOHM3
- DOUPE
- DOFLU
- DOINL
- DOINP
- DOPCN
- and related modules showing the same geographic pattern

However, other module flags showed the opposite pattern. For example, `DOEAH`, `DOPAA`, `DOSBE`, and `DOSLP` were available for the 1,949 territorial respondents rather than the remaining 65,130 respondents.

Therefore, **geography explains some module-availability differences, but not all of them**.


The CCHS PUMF does not provide the same substantive information for every respondent.

Some modules are structurally restricted to particular populations or geographic groups.

Therefore, later feature-selection decisions cannot be based only on whether a variable exists in the CSV. I also need to consider:

- who the variable applies to,
- why some respondents receive valid skips,
- the survey universe of the variable,
- and whether a proposed feature set can be used consistently across the intended modelling population.


## Next question

I now need to investigate the official definitions of the module flags and their associated universes to understand why different modules are available to different respondent groups.

After understanding module applicability, I can begin investigating which outcomes are sufficiently populated and which information domains could realistically be used in a broader prediction experiment.

# Stage 5

## CCHS PUMF Exploration — Stage 5: Module Applicability and Survey Universes

## What I investigated

I used the official CCHS 2022 data dictionary to understand how the `DO...` inclusion flags relate to the variables within each module.

A module-level flag tells us whether a section of the questionnaire is applicable or available for a respondent, but individual variables can also have their own survey universe.

## Key finding

The module-availability patterns observed in Stage 4 are therefore not ordinary missing values.

For example, some variables are only applicable to particular age groups, geographic groups, or respondents who followed a specific path through the questionnaire. When a variable contains `6 = Valid skip`, this can mean that the respondent was outside its universe rather than that information was missing.

The same principle explains why some modules are available only for the territorial respondents while others have the opposite pattern.

## Methodological implication

I should not treat every valid skip as missing and then impute it.

Before using a variable as a feature, I need to check:

- who the variable applies to,
- what its valid-skip codes mean,
- whether its universe is compatible with the intended modelling population,
- and whether the variable can be compared consistently across respondents.

This means that feature availability is part of feature selection, not just a preprocessing issue.

## Research implication

The original 11-feature model should not be treated as the full information available in the CCHS PUMF. However, broader feature sets need to be constructed around variables whose definitions and applicable populations are understood.

Variables with restricted universes can instead be tested in separate population-specific experiments rather than being forced into a single full-sample model.

# Stage 6

In [ ]:
# Show all variables related to health conditions and diseases.
# We are only listing them for inspection at this stage.

health_condition_vars = [
    col for col in df.columns
    if col.startswith(("CCC", "CC1"))
]

print(f"Number of health-condition variables: {len(health_condition_vars)}")
print()

for col in health_condition_vars:
    print(col)

Number of health-condition variables: 11

CCC_05
CCC_80
CCC_85
CCC_90
CCC_135
CCCDGSKL
CCCDGCAR
CC1_140
CC1_145
CC1_155
CC1_170


###What these 11 variables mean



| Variable   | In simple English                                                                         | What kind of information is it? |
| ---------- | ----------------------------------------------------------------------------------------- | ------------------------------- |
| `CCC_05`   | Does the person have diabetes?                                                            | **Our current target**          |
| `CCC_80`   | Does the person have high blood pressure?                                                 | Health condition                |
| `CCC_85`   | Have they taken medicine for high blood pressure in the past month?                       | Treatment/medication            |
| `CCC_90`   | Have they ever been told by a health professional that their cholesterol was high?        | Health condition/history        |
| `CCC_135`  | Does the person have a mood disorder such as depression or bipolar disorder?              | Health condition                |
| `CCCDGSKL` | Does the person have arthritis, fibromyalgia or osteoporosis?                             | Grouped health condition        |
| `CCCDGCAR` | Does the person have heart disease, have had a heart attack, or have effects of a stroke? | Grouped health condition        |
| `CC1_140`  | Does the person have an anxiety disorder?                                                 | Health condition                |
| `CC1_145`  | Does the person have PTSD?                                                                | Health condition                |
| `CC1_155`  | Does the person have chronic fatigue syndrome?                                            | Health condition                |
| `CC1_170`  | Does the person have multiple chemical sensitivities?                                     | Health condition                |



Aside from CCC_05 (the target), these health-condition variables are addressed separately below. See the comorbidity decision in Stage 14.

In [ ]:
# Look at the actual answer counts for each health variable.
# This helps us see how much information each variable contains.

for col in health_condition_vars:
    print(f"\n{'=' * 60}")
    print(col)
    print(df[col].value_counts(dropna=False).sort_index())


CCC_05
CCC_05
1     5994
2    60248
9      837
Name: count, dtype: int64

CCC_80
CCC_80
1    16967
2    49600
9      512
Name: count, dtype: int64

CCC_85
CCC_85
1    17600
2    49161
9      318
Name: count, dtype: int64

CCC_90
CCC_90
1    16869
2    50042
9      168
Name: count, dtype: int64

CCC_135
CCC_135
1     8103
2    58748
9      228
Name: count, dtype: int64

CCCDGSKL
CCCDGSKL
1    19460
2    43054
6     3761
9      804
Name: count, dtype: int64

CCCDGCAR
CCCDGCAR
1     5618
2    46032
6    13884
9     1545
Name: count, dtype: int64

CC1_140
CC1_140
1     9835
2    57052
9      192
Name: count, dtype: int64

CC1_145
CC1_145
1     3027
2    63733
9      319
Name: count, dtype: int64

CC1_155
CC1_155
1      896
2    52079
6    13884
9      220
Name: count, dtype: int64

CC1_170
CC1_170
1     1095
2    51864
6    13884
9      236
Name: count, dtype: int64


## Stage 6 — Health Information Available in CCHS

The health-condition inspection shows that the PUMF contains information on diabetes, high blood pressure, high cholesterol, cardiovascular conditions, and several other diagnosed health conditions.

Most of these variables use `1 = Yes`, `2 = No`, and `9 = Not stated`. Some also contain `6 = Valid skip`, which reflects a variable-specific universe rather than ordinary missing data.

The important modelling issue is that these health-condition variables contain information that may be strongly related to diabetes, but they also describe conditions that may already be part of a respondent's diagnosed health history.

Because of this, I will not automatically add all available health-condition variables to the main feature set. They will be considered separately when evaluating the effect of adding clinical/comorbidity information.

For now, `CCC_05` remains the target, while the other health-condition variables are retained as candidates for later controlled experiments.

# Stage 7

In [ ]:
# Basic demographic, household, geographic, education and income variables
# We are inspecting them only — no modelling or feature selection yet.

demographic_vars = [
    "GEOGPRV",
    "GEODGHR4",
    "DHHDGHSZ",
    "EDDVH3",
    "DHHGAGE",
    "DHH_SEX",
    "INCDGHH",
    "INCDGRCA",
    "INCDGRPR",
    "INCDGRRS"
]

# Show which of these variables are actually present in our dataset
for col in demographic_vars:
    print(col, "->", "Present" if col in df.columns else "NOT FOUND")

GEOGPRV -> Present
GEODGHR4 -> Present
DHHDGHSZ -> Present
EDDVH3 -> Present
DHHGAGE -> Present
DHH_SEX -> Present
INCDGHH -> Present
INCDGRCA -> Present
INCDGRPR -> Present
INCDGRRS -> Present


In [ ]:
# Show the actual answer codes and counts for each variable.

for col in demographic_vars:
    print(f"\n{'=' * 60}")
    print(col)
    print(df[col].value_counts(dropna=False).sort_index())


GEOGPRV
GEOGPRV
10     1869
11      392
12     2571
13     2464
24    13012
35    21526
46     2945
47     2414
48     8290
59     9647
60     1949
Name: count, dtype: int64

GEODGHR4
GEODGHR4
10911     896
10912     428
10913     545
11900     392
12901     630
         ... 
59942     696
59943     483
59951     531
59952     423
60901    1949
Name: count, Length: 91, dtype: int64

DHHDGHSZ
DHHDGHSZ
1    24957
2    41625
9      497
Name: count, dtype: int64

EDDVH3
EDDVH3
1     4736
2    11905
3    48112
9     2326
Name: count, dtype: int64

DHHGAGE
DHHGAGE
1     3761
2    10123
3    12829
4    16399
5    23967
Name: count, dtype: int64

DHH_SEX
DHH_SEX
1    31105
2    35974
Name: count, dtype: int64

INCDGHH
INCDGHH
1     2075
2     8634
3     9737
4     8555
5    37104
9      974
Name: count, dtype: int64

INCDGRCA
INCDGRCA
1    12739
2    13305
3    12546
4    12586
5    12980
6     1949
9      974
Name: count, dtype: int64

INCDGRPR
INCDGRPR
1    12899
2    13188
3    12548
4    

## Stage 7 — Demographic and Socioeconomic Information

The CCHS PUMF provides several demographic and socioeconomic variables, including age, sex at birth, household size, education, province/territory, health region, and household income.

Age is grouped into five categories, while education and household size are also represented as broad categorical variables. Geography is available at both province/territory and health-region levels. Income has several representations, including broad household-income groups and relative income measures.

The different representations are not interchangeable. Some income variables have territorial restrictions, and the more detailed geographic variables may introduce a much larger number of categories.

For feature selection, I therefore need to consider both the meaning and the applicability of a variable rather than automatically including every representation of the same concept.

The original 11-feature model already included age, sex, geography, household size, education and income, so this section mainly helps identify alternative representations and possible additions for later experiments.

No new demographic or socioeconomic variables are added to the modelling dataset at this stage.

# Stage 8

In [ ]:
# Variables related to lifestyle, health behaviours and related measurements

lifestyle_vars = [
    col for col in df.columns
    if col.startswith((
        "SMK",   # smoking
        "CSS",   # current smoking status
        "ECV",   # vaping
        "PAA",   # physical activity
        "EAH",   # eating habits
        "FSC",   # food security
        "HWT"    # height / weight / BMI
    ))
]

print(f"Number of lifestyle-related variables: {len(lifestyle_vars)}")
print()

for col in lifestyle_vars:
    print(col)

Number of lifestyle-related variables: 81

HWTDGISW
HWTDGWHO
HWTDGBCC
EAHG05
EAHDVCHO
EAHDVFFD
EAHDVFRU
EAHDVGRN
EAHDVJUI
EAHDVORA
EAHDVSCD
EAHDVSOD
EAHDVSTA
EAHDVVEG
EAHDVEND
EAHDVBVT
EAHDVBVG
EAHDVFVT
EAHDVFVG
PAA_05
PAA_10A
PAA_10B
PAA_10C
PAA_10D
PAA_10E
PAA_10F
PAA_10G
PAA_15A
PAA_15B
PAA_30
PAA_35
PAA_40A
PAA_40B
PAA_40C
PAA_40D
PAA_40E
PAA_40F
PAA_40G
PAA_45A
PAA_45B
PAA_60
PAA_65
PAA_70A
PAA_70B
PAA_70C
PAA_70D
PAA_70E
PAA_70F
PAA_70G
PAA_75A
PAA_75B
PAA_95
PAA_100A
PAA_100B
PAADVMVA
PAADVACV
PAADVAC2
PAADVVIG
PAADVVOL
PAADVWHO
CSS_05
CSS_15
CSSG20
CSS_25
CSS_30
CSS_40
SMKDVSTY
SMKDGYCS
SMKDGSTP
ECV_05
ECVG15
ECV_20
ECVDVSMK
ECV2G05A
ECV2G05B
ECV2G05C
ECV2_10
ECV2_15
FSCDVAF2
FSCDVCF2
FSCDVHF2


# Stage 9

In [ ]:
# Physical activity variables
# We are only inspecting what information exists here.

activity_vars = [
    col for col in df.columns
    if col.startswith("PAA")
]

print(f"Number of physical-activity variables: {len(activity_vars)}")
print()

for col in activity_vars:
    print(col)

Number of physical-activity variables: 41

PAA_05
PAA_10A
PAA_10B
PAA_10C
PAA_10D
PAA_10E
PAA_10F
PAA_10G
PAA_15A
PAA_15B
PAA_30
PAA_35
PAA_40A
PAA_40B
PAA_40C
PAA_40D
PAA_40E
PAA_40F
PAA_40G
PAA_45A
PAA_45B
PAA_60
PAA_65
PAA_70A
PAA_70B
PAA_70C
PAA_70D
PAA_70E
PAA_70F
PAA_70G
PAA_75A
PAA_75B
PAA_95
PAA_100A
PAA_100B
PAADVMVA
PAADVACV
PAADVAC2
PAADVVIG
PAADVVOL
PAADVWHO


## Stage 9 — Physical Activity Information

We inspected the 41 physical-activity variables available in the CCHS 2022 dataset.

These variables do not represent 41 unrelated characteristics. They form a sequence of related questions covering areas such as:

- active transportation such as walking or cycling
- days on which activity occurred
- time spent doing the activity
- sports, fitness and recreational activity
- vigorous physical activity
- total physical-activity minutes
- overall weekly activity volume
- activity-level indicators based on physical-activity guidelines

The CCHS dataset also contains derived variables that summarise the detailed survey responses into measures such as total minutes of activity and activity-level categories.

### Important finding

The physical-activity section is available to only a restricted group in this particular PUMF.

The official data dictionary shows that the physical-activity inclusion flag is Yes for 1,949 respondents and No for 65,130 respondents. Consequently, many physical-activity variables contain "Valid skip" for most respondents.

This is **not equivalent to ordinary missing data**. It reflects the fact that the physical-activity section was not applicable or available to those respondents.


Physical activity could be scientifically relevant to diabetes prediction, but we cannot simply add these variables to the full 67,079-person dataset without deciding how the restricted availability should be handled.

This means that physical activity may be more suitable for a separate experiment or a carefully defined subset analysis rather than being automatically added to the existing baseline model.

### Research implication

This inspection demonstrates why feature selection must consider not only predictive usefulness, but also:

- who has information available,
- what the variable actually measures,
- whether it is a raw response or a derived summary,
- and whether adding it changes the population being analysed.

No physical-activity variables have been added to the modelling dataset at this stage.

# Stage 10

In [ ]:
# Smoking and vaping variables
# We are only identifying what information exists at this stage.

smoking_vars = [
    col for col in df.columns
    if col.startswith(("CSS", "SMK"))
]

vaping_vars = [
    col for col in df.columns
    if col.startswith("ECV")
]

print("SMOKING VARIABLES")
print("-----------------")
for col in smoking_vars:
    print(col)

print("\nNumber of smoking variables:", len(smoking_vars))

print("\n\nVAPING VARIABLES")
print("----------------")
for col in vaping_vars:
    print(col)

print("\nNumber of vaping variables:", len(vaping_vars))

SMOKING VARIABLES
-----------------
CSS_05
CSS_15
CSSG20
CSS_25
CSS_30
CSS_40
SMKDVSTY
SMKDGYCS
SMKDGSTP

Number of smoking variables: 9


VAPING VARIABLES
----------------
ECV_05
ECVG15
ECV_20
ECVDVSMK
ECV2G05A
ECV2G05B
ECV2G05C
ECV2_10
ECV2_15

Number of vaping variables: 9


In [ ]:
# Inspect the actual answer codes and frequencies
# for smoking and vaping variables.

smoking_vaping_vars = smoking_vars + vaping_vars

for col in smoking_vaping_vars:
    print(f"\n{'=' * 60}")
    print(col)
    print(df[col].value_counts(dropna=False).sort_index())


CSS_05
CSS_05
1    34757
2    32246
9       76
Name: count, dtype: int64

CSS_15
CSS_15
1    27231
2     7317
6    32381
9      150
Name: count, dtype: int64

CSSG20
CSSG20
1     6160
2      680
3    18501
6    39698
9     2040
Name: count, dtype: int64

CSS_25
CSS_25
0          8
1         41
2        102
3        173
4        209
5        404
6        250
7        180
8        299
9         50
10      1090
11        42
12       497
13        95
14        45
15       769
16        27
17        38
18        63
19         4
20       916
21         4
22        11
23         4
24        16
25       576
26         1
27         3
29         1
30        76
32         1
33         1
35        20
36         1
37         3
38         3
40        46
45         5
47         1
48         2
50        37
60         2
70         1
75         3
99         1
996    58879
999     2079
Name: count, dtype: int64

CSS_30
CSS_30
0          2
1        205
2        149
3         75
4         52
5         67


## Stage 10 — Smoking and Vaping Information

We inspected the smoking and vaping information available in the CCHS 2022 dataset.

The dataset contains:

- 9 smoking-related variables
- 9 vaping-related variables

### Smoking information

The smoking variables cover several levels of detail, including:

- whether the respondent has ever smoked a whole cigarette
- whether they have smoked at least 100 cigarettes in their lifetime
- smoking frequency in the past 30 days
- number of cigarettes smoked by daily smokers
- number of cigarettes smoked by occasional smokers
- attempts to quit smoking
- overall smoking status
- years of daily smoking
- years since stopping smoking

The derived smoking-status variable (`SMKDVSTY`) combines several survey responses into broader categories such as current daily smoker, current occasional smoker, former smoker, experimental smoker and lifetime abstainer.

### Vaping information

The vaping variables cover:

- whether the respondent has tried an e-cigarette or vaping device
- vaping behaviour
- the relationship between smoking and vaping
- whether recently used vaping liquid contained nicotine
- whether recently used vaping liquid did not contain nicotine
- whether the liquid had unknown content
- attempts to quit smoking using vaping

### Important finding

The smoking information is available much more broadly than the detailed vaping information.

Several detailed questions have large numbers of `6` values because they were only applicable to particular groups of respondents. These values therefore should not automatically be treated as ordinary missing data.

### Modelling implication

Smoking behaviour could potentially be represented at different levels of detail.

For example, a model could use:

- a broad smoking-status summary, or
- more detailed information such as smoking frequency or cigarette quantity.

These choices are not equivalent and should be decided based on the research question rather than by simply including every available smoking variable.

The same principle applies to vaping.

At this stage, no smoking or vaping variables have been added to the modelling dataset.

# Stage 11

In [ ]:
# Food and eating-habit variables
# We are only identifying the information available at this stage.

food_vars = [
    col for col in df.columns
    if col.startswith(("EAH", "FSC"))
]

print(f"Number of food-related variables: {len(food_vars)}")
print()

for col in food_vars:
    print(col)

Number of food-related variables: 19

EAHG05
EAHDVCHO
EAHDVFFD
EAHDVFRU
EAHDVGRN
EAHDVJUI
EAHDVORA
EAHDVSCD
EAHDVSOD
EAHDVSTA
EAHDVVEG
EAHDVEND
EAHDVBVT
EAHDVBVG
EAHDVFVT
EAHDVFVG
FSCDVAF2
FSCDVCF2
FSCDVHF2


In [ ]:
# Eating-habit variables
# We are only listing the variables for this topic.

eating_vars = [
    col for col in df.columns
    if col.startswith("EAH")
]

print(f"Number of eating-habit variables: {len(eating_vars)}")
print()

for col in eating_vars:
    print(col)

Number of eating-habit variables: 16

EAHG05
EAHDVCHO
EAHDVFFD
EAHDVFRU
EAHDVGRN
EAHDVJUI
EAHDVORA
EAHDVSCD
EAHDVSOD
EAHDVSTA
EAHDVVEG
EAHDVEND
EAHDVBVT
EAHDVBVG
EAHDVFVT
EAHDVFVG


In [ ]:
# Look at the actual values for the 16 eating-habit variables.

for col in eating_vars:
    print(f"\n{'=' * 60}")
    print(col)
    print(df[col].value_counts(dropna=False).sort_index())


EAHG05
EAHG05
0      470
1      621
2      526
3      320
6    65130
9       12
Name: count, dtype: int64

EAHDVCHO
EAHDVCHO
0.0       1733
0.1         54
0.2         12
0.3         21
0.4          8
0.5          5
0.6          2
0.7          4
0.8          1
1.0          8
1.4          1
1.7          1
2.0          6
3.0          4
4.0          1
6.0          1
999.6    65130
999.9       87
Name: count, dtype: int64

EAHDVFFD
EAHDVFFD
0.0       1369
0.1        212
0.2         44
0.3         81
0.4         28
0.5         11
0.6         18
0.7         11
0.8          1
0.9          5
1.0         49
1.4          1
2.0         24
3.0          6
4.0          4
5.0          2
6.0          1
7.0          1
999.6    65130
999.9       81
Name: count, dtype: int64

EAHDVFRU
EAHDVFRU
0.0        139
0.1        220
0.2         53
0.3        169
0.4        137
0.5         47
0.6         94
0.7        106
0.8         15
0.9         23
1.0        520
1.1          5
1.3          6
1.4         12
1.5 

In [ ]:
# Check whether the eating-habits section is exactly the territorial sample.

print("Eating habits available by province/territory:")
print(pd.crosstab(df["GEOGPRV"], df["DOEAH"]))

print("\n\nPhysical activity available by province/territory:")
print(pd.crosstab(df["GEOGPRV"], df["DOPAA"]))

Eating habits available by province/territory:
DOEAH        0     1
GEOGPRV             
10        1869     0
11         392     0
12        2571     0
13        2464     0
24       13012     0
35       21526     0
46        2945     0
47        2414     0
48        8290     0
59        9647     0
60           0  1949


Physical activity available by province/territory:
DOPAA        0     1
GEOGPRV             
10        1869     0
11         392     0
12        2571     0
13        2464     0
24       13012     0
35       21526     0
46        2945     0
47        2414     0
48        8290     0
59        9647     0
60           0  1949


## Stage 11 — Eating Habits and Food Information

The food-related section contains 19 variables:

- 16 eating-habit variables (`EAH...`)
- 3 food-security variables (`FSC...`)

The eating-habit variables describe food and beverage consumption, including fruit, vegetables, restaurant food, beverages, and derived consumption measures. Several variables represent related or derived versions of the same underlying behaviour, so they should not automatically be treated as independent predictors.

A major structural limitation is that the detailed eating-habit module is available only for the 1,949 respondents in the territorial component of this PUMF (`DOEAH = 1`). The remaining 65,130 respondents have structural skips because the module was not available to them. Therefore, these values should not be treated as ordinary missing observations or imputed into the full dataset.

Food-security information is much more broadly available. In particular, `FSCDVHF2` represents household food security across the respondent file and was therefore practical for the original baseline model.

This distinction means that detailed dietary variables would define a different modelling experiment, potentially involving a much smaller and geographically different population. They will therefore not be added automatically to the main full-sample feature set.

**Current decision:** retain `FSCDVHF2` as the broad food-security representation, while treating detailed eating-habit variables as candidates for a separate restricted-population experiment.

# Stage 12

In [ ]:
# Stage 12 — Applicability Audit
# Step 1: Find all CCHS module/inclusion flags

do_columns = [col for col in df.columns if col.startswith("DO")]

print(f"Number of DO/inclusion-flag variables: {len(do_columns)}")
print("\nThese are the availability/applicability flags found in the dataset:\n")

for col in do_columns:
    print(col)

Number of DO/inclusion-flag variables: 31

These are the availability/applicability flags found in the dataset:

DOMAC
DOGEN
DOLSM
DOHWT
DOWTP
DOCOV2
DOCOV3
DOCCC
DOCC1
DOWDM
DOOHM
DOOHM3
DOEAH
DOPAA
DOUPE
DOSBE
DOSLP
DOCSS
DOSPU
DOECV
DOECV2
DOALC
DOCAN
DOFLU
DORHC
DOLMAM
DOLAN
DOINL
DOINP
DOPCN
DOFSC


In [ ]:
# Step 2: Count how many respondents are included/excluded
# for every DO/inclusion flag.

for col in do_columns:
    counts = df[col].value_counts(dropna=False).sort_index()

    print(f"\n{'=' * 60}")
    print(f"{col}")
    print(counts)


DOMAC
DOMAC
1    67079
Name: count, dtype: int64

DOGEN
DOGEN
1    67079
Name: count, dtype: int64

DOLSM
DOLSM
1    67079
Name: count, dtype: int64

DOHWT
DOHWT
1    67079
Name: count, dtype: int64

DOWTP
DOWTP
1    67079
Name: count, dtype: int64

DOCOV2
DOCOV2
1    67079
Name: count, dtype: int64

DOCOV3
DOCOV3
1    67079
Name: count, dtype: int64

DOCCC
DOCCC
1    67079
Name: count, dtype: int64

DOCC1
DOCC1
1    67079
Name: count, dtype: int64

DOWDM
DOWDM
0     1949
1    65130
Name: count, dtype: int64

DOOHM
DOOHM
0     1949
1    65130
Name: count, dtype: int64

DOOHM3
DOOHM3
0     1949
1    65130
Name: count, dtype: int64

DOEAH
DOEAH
0    65130
1     1949
Name: count, dtype: int64

DOPAA
DOPAA
0    65130
1     1949
Name: count, dtype: int64

DOUPE
DOUPE
0     1949
1    65130
Name: count, dtype: int64

DOSBE
DOSBE
0    65130
1     1949
Name: count, dtype: int64

DOSLP
DOSLP
0    65130
1     1949
Name: count, dtype: int64

DOCSS
DOCSS
1    67079
Name: count, dtype: int64

DOSPU

In [ ]:
# Step 3 — Compare every varying module flag with geography.
# This tells us whether the restriction is tied to the
# province/territory split.

varying_do_columns = []

for col in do_columns:
    unique_values = df[col].dropna().unique()

    if len(unique_values) > 1:
        varying_do_columns.append(col)

print(f"Varying DO flags: {len(varying_do_columns)}")
print(varying_do_columns)

for col in varying_do_columns:
    print(f"\n{'=' * 70}")
    print(f"{col} by province/territory")
    print(pd.crosstab(df["GEOGPRV"], df[col]))

Varying DO flags: 12
['DOWDM', 'DOOHM', 'DOOHM3', 'DOEAH', 'DOPAA', 'DOUPE', 'DOSBE', 'DOSLP', 'DOFLU', 'DOINL', 'DOINP', 'DOPCN']

DOWDM by province/territory
DOWDM       0      1
GEOGPRV             
10          0   1869
11          0    392
12          0   2571
13          0   2464
24          0  13012
35          0  21526
46          0   2945
47          0   2414
48          0   8290
59          0   9647
60       1949      0

DOOHM by province/territory
DOOHM       0      1
GEOGPRV             
10          0   1869
11          0    392
12          0   2571
13          0   2464
24          0  13012
35          0  21526
46          0   2945
47          0   2414
48          0   8290
59          0   9647
60       1949      0

DOOHM3 by province/territory
DOOHM3      0      1
GEOGPRV             
10          0   1869
11          0    392
12          0   2571
13          0   2464
24          0  13012
35          0  21526
46          0   2945
47          0   2414
48          0   8290
59  

In [ ]:
# Step 4 — Create a compact summary of the varying flags.

summary_rows = []

for col in varying_do_columns:
    cross = pd.crosstab(df["GEOGPRV"], df[col])

    summary_rows.append({
        "Variable": col,
        "Distinct_values": df[col].nunique(),
        "Count_0": (df[col] == 0).sum(),
        "Count_1": (df[col] == 1).sum(),
        "Same_territory_split": (
            (df.loc[df["GEOGPRV"] == 60, col].nunique() == 1)
            and
            (df.loc[df["GEOGPRV"] != 60, col].nunique() == 1)
        )
    })

do_audit_summary = pd.DataFrame(summary_rows)

do_audit_summary

,Variable,Distinct_values,Count_0,Count_1,Same_territory_split
0,DOWDM,2,1949,65130,True
1,DOOHM,2,1949,65130,True
2,DOOHM3,2,1949,65130,True
3,DOEAH,2,65130,1949,True
4,DOPAA,2,65130,1949,True
5,DOUPE,2,1949,65130,True
6,DOSBE,2,65130,1949,True
7,DOSLP,2,65130,1949,True
8,DOFLU,2,1949,65130,True
9,DOINL,2,1949,65130,True


In [ ]:
# Step 5 — Summarize all DO flags whose applicability
# is perfectly determined by province vs territory.

geographic_do_summary = []

for col in varying_do_columns:
    province_values = df.loc[df["GEOGPRV"] != 60, col].unique()
    territory_values = df.loc[df["GEOGPRV"] == 60, col].unique()

    geographic_do_summary.append({
        "Module_flag": col,
        "Province_value": province_values.tolist(),
        "Territory_value": territory_values.tolist(),
        "Province_n": (df["GEOGPRV"] != 60).sum(),
        "Territory_n": (df["GEOGPRV"] == 60).sum(),
        "Perfect_geographic_split": (
            len(province_values) == 1 and
            len(territory_values) == 1
        )
    })

geographic_do_summary = pd.DataFrame(geographic_do_summary)

geographic_do_summary

,Module_flag,Province_value,Territory_value,Province_n,Territory_n,Perfect_geographic_split
0,DOWDM,[1],[0],65130,1949,True
1,DOOHM,[1],[0],65130,1949,True
2,DOOHM3,[1],[0],65130,1949,True
3,DOEAH,[0],[1],65130,1949,True
4,DOPAA,[0],[1],65130,1949,True
5,DOUPE,[1],[0],65130,1949,True
6,DOSBE,[0],[1],65130,1949,True
7,DOSLP,[0],[1],65130,1949,True
8,DOFLU,[1],[0],65130,1949,True
9,DOINL,[1],[0],65130,1949,True


In [ ]:
# Step 6 — Separate the geographically restricted flags
# from flags that apply to everyone.

print("Geographically restricted modules:")
display(
    geographic_do_summary[
        geographic_do_summary["Perfect_geographic_split"]
    ]
)

print("\nDO flags applying to everyone:")
display(
    [
        col for col in do_columns
        if df[col].nunique(dropna=True) == 1
    ]
)

Geographically restricted modules:


,Module_flag,Province_value,Territory_value,Province_n,Territory_n,Perfect_geographic_split
0,DOWDM,[1],[0],65130,1949,True
1,DOOHM,[1],[0],65130,1949,True
2,DOOHM3,[1],[0],65130,1949,True
3,DOEAH,[0],[1],65130,1949,True
4,DOPAA,[0],[1],65130,1949,True
5,DOUPE,[1],[0],65130,1949,True
6,DOSBE,[0],[1],65130,1949,True
7,DOSLP,[0],[1],65130,1949,True
8,DOFLU,[1],[0],65130,1949,True
9,DOINL,[1],[0],65130,1949,True



DO flags applying to everyone:


['DOMAC',
 'DOGEN',
 'DOLSM',
 'DOHWT',
 'DOWTP',
 'DOCOV2',
 'DOCOV3',
 'DOCCC',
 'DOCC1',
 'DOCSS',
 'DOSPU',
 'DOECV',
 'DOECV2',
 'DOALC',
 'DOCAN',
 'DORHC',
 'DOLMAM',
 'DOLAN',
 'DOFSC']

In [ ]:
# Stage 12 — Step 7
# List variables belonging to each module without
# accidentally including longer module names.

restricted_modules = [col[2:] for col in varying_do_columns]

for module in restricted_modules:
    module_vars = [
        col for col in df.columns
        if col.startswith(module + "_") or
           col.startswith(module + "D") or
           col.startswith(module + "G")
    ]

    print(f"\n{'=' * 70}")
    print(f"Module: {module}")
    print(f"Number of variables: {len(module_vars)}")
    print(module_vars)


Module: WDM
Number of variables: 1
['WDMDGDIF']

Module: OHM
Number of variables: 2
['OHM_05', 'OHM_15']

Module: OHM3
Number of variables: 14
['OHM3_05', 'OHM3_10', 'OHM3_15', 'OHM3_18', 'OHM3_20A', 'OHM3_20B', 'OHM3_20C', 'OHM3_20D', 'OHM3_20E', 'OHM3_20F', 'OHM3_45', 'OHM3G50A', 'OHM3_50C', 'OHM3_50E']

Module: EAH
Number of variables: 16
['EAHG05', 'EAHDVCHO', 'EAHDVFFD', 'EAHDVFRU', 'EAHDVGRN', 'EAHDVJUI', 'EAHDVORA', 'EAHDVSCD', 'EAHDVSOD', 'EAHDVSTA', 'EAHDVVEG', 'EAHDVEND', 'EAHDVBVT', 'EAHDVBVG', 'EAHDVFVT', 'EAHDVFVG']

Module: PAA
Number of variables: 41
['PAA_05', 'PAA_10A', 'PAA_10B', 'PAA_10C', 'PAA_10D', 'PAA_10E', 'PAA_10F', 'PAA_10G', 'PAA_15A', 'PAA_15B', 'PAA_30', 'PAA_35', 'PAA_40A', 'PAA_40B', 'PAA_40C', 'PAA_40D', 'PAA_40E', 'PAA_40F', 'PAA_40G', 'PAA_45A', 'PAA_45B', 'PAA_60', 'PAA_65', 'PAA_70A', 'PAA_70B', 'PAA_70C', 'PAA_70D', 'PAA_70E', 'PAA_70F', 'PAA_70G', 'PAA_75A', 'PAA_75B', 'PAA_95', 'PAA_100A', 'PAA_100B', 'PAADVMVA', 'PAADVACV', 'PAADVAC2', 'PAADVVIG

In [ ]:
# Stage 12 — Step 8
# Compact summary of geographically restricted modules.

module_summary = []

for module in restricted_modules:
    flag = "DO" + module

    module_vars = [
        col for col in df.columns
        if col.startswith(module + "_") or
           col.startswith(module + "D") or
           col.startswith(module + "G")
    ]

    module_summary.append({
        "Module": module,
        "Availability_flag": flag,
        "Number_of_variables": len(module_vars),
        "Province_available": df.loc[df["GEOGPRV"] != 60, flag].iloc[0],
        "Territory_available": df.loc[df["GEOGPRV"] == 60, flag].iloc[0],
        "Total_respondents": len(df)
    })

module_summary = pd.DataFrame(module_summary)

module_summary

,Module,Availability_flag,Number_of_variables,Province_available,Territory_available,Total_respondents
0,WDM,DOWDM,1,1,0,67079
1,OHM,DOOHM,2,1,0,67079
2,OHM3,DOOHM3,14,1,0,67079
3,EAH,DOEAH,16,0,1,67079
4,PAA,DOPAA,41,0,1,67079
5,UPE,DOUPE,18,1,0,67079
6,SBE,DOSBE,2,0,1,67079
7,SLP,DOSLP,4,0,1,67079
8,FLU,DOFLU,9,1,0,67079
9,INL,DOINL,1,1,0,67079


# Stage 13

In [ ]:
# ============================================================
# STAGE 13 — FINAL CANDIDATE-POOL CONSTRUCTION
# Step 1: Separate target, survey flags, and ordinary variables
# ============================================================

target = "CCC_05"

do_columns = [col for col in df.columns if col.startswith("DO")]

# Known target
target_columns = [target]

# Variables that should not be treated as ordinary predictors
excluded_structural = sorted(set(do_columns + target_columns))

candidate_pool_initial = [
    col for col in df.columns
    if col not in excluded_structural
]

print("Total variables:", len(df.columns))
print("Target variable:", target)
print("Survey/inclusion flag variables:", len(do_columns))
print("Initial candidate pool:", len(candidate_pool_initial))

print("\nExcluded structural variables:")
print(excluded_structural)

Total variables: 255
Target variable: CCC_05
Survey/inclusion flag variables: 31
Initial candidate pool: 223

Excluded structural variables:
['CCC_05', 'DOALC', 'DOCAN', 'DOCC1', 'DOCCC', 'DOCOV2', 'DOCOV3', 'DOCSS', 'DOEAH', 'DOECV', 'DOECV2', 'DOFLU', 'DOFSC', 'DOGEN', 'DOHWT', 'DOINL', 'DOINP', 'DOLAN', 'DOLMAM', 'DOLSM', 'DOMAC', 'DOOHM', 'DOOHM3', 'DOPAA', 'DOPCN', 'DORHC', 'DOSBE', 'DOSLP', 'DOSPU', 'DOUPE', 'DOWDM', 'DOWTP']


In [ ]:
# Show the 223 variables currently in the candidate pool

for i, col in enumerate(candidate_pool_initial, start=1):
    print(f"{i:3}. {col}")

  1. VERDATE
  2. REFPER
  3. ADM_RNO
  4. COLMODE
  5. COLMODEY
  6. COLMODEP
  7. GEOGPRV
  8. GEODGHR4
  9. DHHDGHSZ
 10. EDDVH3
 11. DHHGAGE
 12. DHH_SEX
 13. MAC_05
 14. GEN_01
 15. GEN_05
 16. GEN_10
 17. GEN_15
 18. GEN_20
 19. LSM_01
 20. LSMDVSWL
 21. HWTDGISW
 22. HWTDGWHO
 23. HWTDGBCC
 24. WTP_50
 25. COV2_005
 26. COV2_10A
 27. COV2_10B
 28. COV2_10C
 29. COV2_10D
 30. COV2_10E
 31. COV2_10F
 32. COV2_10G
 33. COV2_10H
 34. COV2_10I
 35. COV2_10J
 36. COV2_038
 37. COV2_030
 38. COV2_035
 39. COV2_041
 40. COV2_45A
 41. COV2_45B
 42. COV2_45C
 43. COV2_45D
 44. COV2_45E
 45. COV2_45F
 46. COV2_45G
 47. COV2_45H
 48. COV2_45I
 49. COV2_040
 50. COV3_005
 51. CCC_80
 52. CCC_85
 53. CCC_90
 54. CCC_135
 55. CCCDGSKL
 56. CCCDGCAR
 57. CC1_140
 58. CC1_145
 59. CC1_155
 60. CC1_170
 61. WDMDGDIF
 62. OHM_05
 63. OHM_15
 64. OHM3_05
 65. OHM3_10
 66. OHM3_15
 67. OHM3_18
 68. OHM3_20A
 69. OHM3_20B
 70. OHM3_20C
 71. OHM3_20D
 72. OHM3_20E
 73. OHM3_20F
 74. OHM3_45
 75. OHM3G

In [ ]:
# ============================================================
# STAGE 13 — Step 2
# Remove clear metadata, record identifiers, and survey weights
# ============================================================

clear_non_predictors = [
    "VERDATE",
    "REFPER",
    "ADM_RNO",
    "COLMODE",
    "COLMODEY",
    "COLMODEP",
    "WTS_M"
]

candidate_pool_stage1 = [
    col for col in candidate_pool_initial
    if col not in clear_non_predictors
]

print("Initial candidate pool:", len(candidate_pool_initial))
print("Clear non-predictors removed:", len(clear_non_predictors))
print("Remaining candidate pool:", len(candidate_pool_stage1))

print("\nRemoved:")
print(clear_non_predictors)

Initial candidate pool: 223
Clear non-predictors removed: 7
Remaining candidate pool: 216

Removed:
['VERDATE', 'REFPER', 'ADM_RNO', 'COLMODE', 'COLMODEY', 'COLMODEP', 'WTS_M']


In [ ]:
# ============================================================
# STAGE 13 — Step 3
# See how the 216 candidate variables are distributed
# ============================================================

from collections import Counter

# First 3 characters usually identify the questionnaire section/module.
prefix_counts = Counter(col[:3] for col in candidate_pool_stage1)

module_map = (
    pd.DataFrame(
        prefix_counts.items(),
        columns=["Prefix", "Number_of_variables"]
    )
    .sort_values("Prefix")
    .reset_index(drop=True)
)

print("Number of distinct sections represented:", len(module_map))
display(module_map)

Number of distinct sections represented: 33


,Prefix,Number_of_variables
0,ALC,5
1,CAN,12
2,CC1,4
3,CCC,6
4,COV,26
5,CSS,6
6,DHH,3
7,EAH,16
8,ECV,9
9,EDD,1


In [ ]:
# ============================================================
# STAGE 13 — Step 4
# Preliminary screening of candidate sections
# ============================================================

section_screening = {
    "ALC":  ("KEEP", "Alcohol use / drinking behaviour"),
    "CAN": ("REVIEW", "Cannabis use and medical-purpose cannabis use; relevance to diabetes prediction is indirect"),
    "CC1":  ("REVIEW", "Chronic-condition information; possible overlap with existing health status"),
    "CCC":  ("REVIEW", "Other chronic conditions; possible overlap with diabetes/health status"),
    "COV":  ("REVIEW", "COVID-era health, behaviour and vaccination information; context-specific"),
    "CSS":  ("KEEP", "Current smoking behaviour"),
    "DHH":  ("KEEP", "Demographic characteristics"),
    "EAH":  ("RESTRICTED", "Eating habits; geographically restricted in this PUMF"),
    "ECV":  ("KEEP", "Electronic cigarette / vaping behaviour"),
    "EDD":  ("KEEP", "Education"),
    "FLU":  ("RESTRICTED", "Flu vaccination information; geographically restricted in this PUMF"),
    "FSC":  ("KEEP", "Food security"),
    "GEN":  ("REVIEW", "General and mental health / stress; some variables may be broad health proxies"),
    "GEO":  ("REVIEW", "Geographic information; useful but may act as a strong location proxy"),
    "HWT":  ("KEEP", "Height/weight and BMI-related information"),
    "INC":  ("KEEP", "Household income"),
    "INL":  ("RESTRICTED", "Long-term-care insurance; geographically restricted in this PUMF"),
    "INP":  ("RESTRICTED", "Prescription-medication insurance; geographically restricted in this PUMF"),
    "LBF":  ("KEEP", "Labour-force / employment characteristics"),
    "LSM":  ("REVIEW", "Life satisfaction; plausible but indirect health-related information"),
    "MAC":  ("KEEP", "Main activity"),
    "OHM":  ("RESTRICTED", "Oral health; geographically restricted in this PUMF"),
    "PAA":  ("RESTRICTED", "Physical activity; geographically restricted in this PUMF"),
    "PCN":  ("RESTRICTED", "Prescription use / cost-related non-adherence; geographically restricted in this PUMF"),
    "RHC":  ("KEEP", "Regular health-care provider"),
    "SBE":  ("RESTRICTED", "Sedentary screen behaviour; geographically restricted in this PUMF"),
    "SDC":  ("KEEP", "Selected socio-demographic characteristics"),
    "SLP":  ("RESTRICTED", "Sleep; geographically restricted in this PUMF"),
    "SMK":  ("KEEP", "Smoking-derived measures"),
    "SPU":  ("KEEP", "Smoking past-use information"),
    "UPE":  ("RESTRICTED", "Sport/recreation and protective-equipment behaviours; geographically restricted"),
    "WDM":  ("RESTRICTED", "Disability / functioning measure; geographically restricted in this PUMF"),
    "WTP":  ("KEEP", "Self-perceived weight")
}

screening_rows = []

for prefix, count in prefix_counts.items():
    status, reason = section_screening.get(
        prefix,
        ("REVIEW", "Section not yet classified")
    )

    screening_rows.append({
        "Section": prefix,
        "Variables": count,
        "Status": status,
        "Reason": reason
    })

screening_table = (
    pd.DataFrame(screening_rows)
    .sort_values("Section")
    .reset_index(drop=True)
)

display(screening_table)

print("\nStatus counts:")
print(screening_table["Status"].value_counts())

,Section,Variables,Status,Reason
0,ALC,5,KEEP,Alcohol use / drinking behaviour
1,CAN,12,REVIEW,Cannabis use and medical-purpose cannabis use;...
2,CC1,4,REVIEW,Chronic-condition information; possible overla...
3,CCC,6,REVIEW,Other chronic conditions; possible overlap wit...
4,COV,26,REVIEW,"COVID-era health, behaviour and vaccination in..."
5,CSS,6,KEEP,Current smoking behaviour
6,DHH,3,KEEP,Demographic characteristics
7,EAH,16,RESTRICTED,Eating habits; geographically restricted in th...
8,ECV,9,KEEP,Electronic cigarette / vaping behaviour
9,EDD,1,KEEP,Education



Status counts:
Status
KEEP          15
RESTRICTED    11
REVIEW         7
Name: count, dtype: int64


In [ ]:
# ============================================================
# STAGE 13 — Step 5
# Build the three conceptual candidate pools
# Corrected for 3-character and 4-character CCHS modules
# ============================================================

core_sections = [
    "ALC",
    "CSS",
    "DHH",
    "EDD",
    "ECV",
    "ECV2",
    "FSC",
    "HWT",
    "INC",
    "LBF",
    "MAC",
    "RHC",
    "SDC",
    "SMK",
    "SPU",
    "WTP"
]

review_sections = [
    "CAN",
    "CC1",
    "CCC",
    "COV2",
    "COV3",
    "GEN",
    "LSM"
]

restricted_sections = [
    "EAH",
    "FLU",
    "INL",
    "INP",
    "OHM",
    "OHM3",
    "PAA",
    "PCN",
    "SBE",
    "SLP",
    "UPE",
    "WDM"
]


# ------------------------------------------------------------
# Exact section matching
# ------------------------------------------------------------
def belongs_to_section(column, section):
    return (
        column.startswith(section + "_") or
        column.startswith(section + "D") or
        column.startswith(section + "G")
    )


# ------------------------------------------------------------
# Build pools
# ------------------------------------------------------------
core_pool = [
    col for col in candidate_pool_stage1
    if any(belongs_to_section(col, s) for s in core_sections)
    or col == "EDDVH3"
    or col == "GEOGPRV"
]

review_pool = [
    col for col in candidate_pool_stage1
    if any(belongs_to_section(col, s) for s in review_sections)
    or col == "GEODGHR4"
]

restricted_pool = [
    col for col in candidate_pool_stage1
    if any(belongs_to_section(col, s) for s in restricted_sections)
]


# ------------------------------------------------------------
# Check that every candidate was classified exactly once
# ------------------------------------------------------------
assigned = core_pool + review_pool + restricted_pool

print("Core pool:", len(core_pool))
print("Review pool:", len(review_pool))
print("Restricted pool:", len(restricted_pool))
print("Total assigned:", len(assigned))
print("Original candidate pool:", len(candidate_pool_stage1))

unclassified = [
    col for col in candidate_pool_stage1
    if col not in assigned
]

print("\nUnclassified variables:", len(unclassified))
print(unclassified)

Core pool: 49
Review pool: 56
Restricted pool: 111
Total assigned: 216
Original candidate pool: 216

Unclassified variables: 0
[]


## Stage 13 — Candidate Pool Construction

After excluding the diabetes target (`CCC_05`) and the 31 CCHS `DO...` survey/applicability flags, 223 variables remained for further screening.

Seven additional variables were removed because they represent file metadata, record identification, collection-process information, or the CCHS sampling weight:

- `VERDATE`
- `REFPER`
- `ADM_RNO`
- `COLMODE`
- `COLMODEY`
- `COLMODEP`
- `WTS_M`

This produced a working pool of **216 variables**.

The 216 variables were then organized into three working categories based on the earlier applicability and domain review:

- **Core:** 49 variables suitable for consideration in the main full-population modelling experiments.
- **Review:** 56 variables requiring additional scientific or methodological consideration.
- **Restricted:** 111 variables affected by structural or geographic restrictions and therefore not suitable for automatic inclusion in the main full-sample experiment.

The section-matching procedure was corrected to distinguish four-character modules such as `COV2`, `COV3`, and `ECV2`, and to keep `OHM` and `OHM3` separate. `EDDVH3` and `GEOGPRV` were handled explicitly as exceptions.

The final audit assigned all 216 variables to exactly one pool:

**49 Core + 56 Review + 111 Restricted = 216**

with **0 unclassified variables**.

These categories are working research classifications for this project; they are not classifications defined by Statistics Canada.

The purpose of this stage is to establish a transparent candidate space for the subsequent documentation-, domain-, literature-, and data-driven feature-selection experiments. It does not determine the final feature set.

# Stage 14

In [ ]:
# ============================================================
# STAGE 14 — CCHS Documentation- and Domain-Guided Feature Selection
# Step 1: Rebuild the corrected Core-variable groups
# ============================================================

core_section_groups = {}

for col in core_pool:
    matched_section = None

    for section in core_sections:
        if belongs_to_section(col, section):
            matched_section = section
            break

    # Explicitly handled exceptions
    if matched_section is None and col == "EDDVH3":
        matched_section = "EDD"

    if matched_section is None and col == "GEOGPRV":
        matched_section = "GEO"

    if matched_section is not None:
        core_section_groups.setdefault(
            matched_section, []
        ).append(col)

for section in sorted(core_section_groups):
    print("\n" + "=" * 60)
    print(f"Section: {section}")
    print(f"Number of variables: {len(core_section_groups[section])}")
    print(core_section_groups[section])

print("\nTotal Core variables:", len(core_pool))


Section: ALC
Number of variables: 5
['ALC_05', 'ALC_10', 'ALC_15', 'ALC_20', 'ALCDVTTM']

Section: CSS
Number of variables: 6
['CSS_05', 'CSS_15', 'CSSG20', 'CSS_25', 'CSS_30', 'CSS_40']

Section: DHH
Number of variables: 3
['DHHDGHSZ', 'DHHGAGE', 'DHH_SEX']

Section: ECV
Number of variables: 4
['ECV_05', 'ECVG15', 'ECV_20', 'ECVDVSMK']

Section: ECV2
Number of variables: 5
['ECV2G05A', 'ECV2G05B', 'ECV2G05C', 'ECV2_10', 'ECV2_15']

Section: EDD
Number of variables: 1
['EDDVH3']

Section: FSC
Number of variables: 3
['FSCDVAF2', 'FSCDVCF2', 'FSCDVHF2']

Section: GEO
Number of variables: 1
['GEOGPRV']

Section: HWT
Number of variables: 3
['HWTDGISW', 'HWTDGWHO', 'HWTDGBCC']

Section: INC
Number of variables: 4
['INCDGHH', 'INCDGRCA', 'INCDGRPR', 'INCDGRRS']

Section: LBF
Number of variables: 3
['LBFDGHPW', 'LBFDVPFT', 'LBFDGWSS']

Section: MAC
Number of variables: 1
['MAC_05']

Section: RHC
Number of variables: 1
['RHC_05']

Section: SDC
Number of variables: 3
['SDCDGIMM', 'SDCDVABT', '

| Section             | What it represents                                          | Initial view                       |
| ------------------- | ----------------------------------------------------------- | ---------------------------------- |
| **DHH**             | Age, sex, household size                                    | **Definitely include**             |
| **HWT**             | BMI / weight classification                                 | **Definitely include**             |
| **INC**             | Household income                                            | **Include**                        |
| **EDD**             | Education                                                   | **Include**                        |
| **GEO**             | Province/territory                                          | **Include**                        |
| **FSC**             | Food security                                               | **Include**                        |
| **CSS / SMK / SPU** | Smoking history/status                                      | **Include, but avoid duplication** |
| **ECV / ECV2**      | Vaping                                                      | **Probably include**               |
| **ALC**             | Alcohol use                                                 | **Include**                        |
| **MAC**             | Main activity                                               | **Probably include**               |
| **LBF**             | Employment/work characteristics                             | **Probably include**               |
| **RHC**             | Regular healthcare provider                                 | **Possibly include**               |
| **SDC**             | Immigration / Indigenous identity / visible minority status | **Include cautiously**             |
| **WTP**             | Self-perceived weight                                       | **Include cautiously**             |


In [5]:
# ============================================================
# STAGE 14 — Step 2
# Documentation- and domain-guided section-level screening
# ============================================================

documentation_domain_screening = {
    "DHH": ("A", "Basic demographic characteristics: age, sex, household size"),
    "HWT": ("A", "BMI and weight-related information; directly relevant to metabolic health"),
    "INC": ("A", "Household income; socioeconomic context"),
    "EDD": ("A", "Education; socioeconomic and demographic context"),
    "GEO": ("A", "Province/territory; retained because geography was part of the baseline"),
    "FSC": ("A", "Food security; relevant socioeconomic and lifestyle context"),
    "ALC": ("A", "Alcohol-use behaviour; plausible lifestyle characteristic"),

    "CSS": ("B", "Smoking information is relevant but overlaps with SMK and SPU"),
    "SMK": ("B", "Derived smoking information is useful but overlaps with CSS and SPU"),
    "SPU": ("B", "Past smoking history is useful but should not be redundantly represented"),
    "ECV": ("B", "Vaping is potentially relevant but contains overlapping measures"),
    "ECV2": ("B", "Additional vaping detail; likely requires selective representation"),
    "LBF": ("B", "Employment/work characteristics may add socioeconomic information"),
    "MAC": ("B", "Main activity is potentially useful but overlaps with employment-related information"),
    "SDC": ("B", "Additional demographic/social characteristics; useful but requires careful interpretation"),
    "WTP": ("B", "Self-perceived weight is relevant but overlaps with BMI information"),

    "RHC": ("C", "Healthcare access may improve prediction but shifts the model toward healthcare-context information")
}

documentation_domain_rows = []

for section in sorted(documentation_domain_screening):
    decision, reason = documentation_domain_screening[section]

    documentation_domain_rows.append({
        "Section": section,
        "Decision": decision,
        "Reason": reason
    })

documentation_domain_table = pd.DataFrame(documentation_domain_rows)
display(documentation_domain_table)

print("\nDecision counts:")
print(documentation_domain_table["Decision"].value_counts().sort_index())

,Section,Decision,Reason
0,ALC,A,Alcohol-use behaviour; plausible lifestyle cha...
1,CSS,B,Smoking information is relevant but overlaps w...
2,DHH,A,"Basic demographic characteristics: age, sex, h..."
3,ECV,B,Vaping is potentially relevant but contains ov...
4,ECV2,B,Additional vaping detail; likely requires sele...
5,EDD,A,Education; socioeconomic and demographic context
6,FSC,A,Food security; relevant socioeconomic and life...
7,GEO,A,Province/territory; retained because geography...
8,HWT,A,BMI and weight-related information; directly r...
9,INC,A,Household income; socioeconomic context



Decision counts:
Decision
A    7
B    9
C    1
Name: count, dtype: int64


In [ ]:
# ============================================================
# STAGE 14 — Step 3
# Select variables from the "A — Definitely Include" sections
# ============================================================

research_guided_A = [
    # Alcohol
    "ALCDVTTM",

    # Demographics
    "DHHDGHSZ",
    "DHHGAGE",
    "DHH_SEX",

    # Education
    "EDDVH3",

    # Food security
    "FSCDVHF2",

    # Geography
    "GEOGPRV",

    # BMI / weight
    "HWTDGISW",
    "HWTDGWHO",

    # Income
    "INCDGHH"
]

print("Number of A-section variables selected:", len(research_guided_A))

print("\nSelected variables:")
for i, col in enumerate(research_guided_A, start=1):
    print(f"{i:2}. {col}")

print("\nBaseline variables already represented:")
baseline_overlap = [
    col for col in research_guided_A
    if col in [
        "DHHGAGE",
        "DHH_SEX",
        "GEOGPRV",
        "DHHDGHSZ",
        "EDDVH3",
        "FSCDVHF2",
        "HWTDGISW",
        "INCDGHH"
    ]
]

print(baseline_overlap)

print(
    "\nNew variables added beyond the original baseline:",
    [col for col in research_guided_A if col not in baseline_overlap]
)

Number of A-section variables selected: 10

Selected variables:
 1. ALCDVTTM
 2. DHHDGHSZ
 3. DHHGAGE
 4. DHH_SEX
 5. EDDVH3
 6. FSCDVHF2
 7. GEOGPRV
 8. HWTDGISW
 9. HWTDGWHO
10. INCDGHH

Baseline variables already represented:
['DHHDGHSZ', 'DHHGAGE', 'DHH_SEX', 'EDDVH3', 'FSCDVHF2', 'GEOGPRV', 'HWTDGISW', 'INCDGHH']

New variables added beyond the original baseline: ['ALCDVTTM', 'HWTDGWHO']


In [ ]:
# ============================================================
# STAGE 14 — Step 4
# Check the actual applicability of the selected A variables
# ============================================================

a_variable_checks = [
    "ALCDVTTM",
    "DHHDGHSZ",
    "DHHGAGE",
    "DHH_SEX",
    "EDDVH3",
    "FSCDVHF2",
    "GEOGPRV",
    "HWTDGISW",
    "HWTDGWHO",
    "INCDGHH"
]

print("Selected A-section variables:")
for col in a_variable_checks:
    print(col)

Selected A-section variables:
ALCDVTTM
DHHDGHSZ
DHHGAGE
DHH_SEX
EDDVH3
FSCDVHF2
GEOGPRV
HWTDGISW
HWTDGWHO
INCDGHH


In [ ]:
# ============================================================
# STAGE 14 — Step 4A
# Smoking: documentation- and domain-guided decision
# ============================================================

smoking_main_candidate = []

smoking_adult_experiment = [
    "SMKDVSTY"
]

print("Smoking variables reserved for the main full-population model:")
print(smoking_main_candidate)

print("\nSmoking variable reserved for a possible adult-only experiment:")
print(smoking_adult_experiment)

Smoking variables reserved for the main full-population model:
[]

Smoking variable reserved for a possible adult-only experiment:
['SMKDVSTY']


In [ ]:
# ============================================================
# STAGE 14 — Step 4B
# Vaping: documentation- and domain-guided decision
# ============================================================

vaping_main_candidates = [
    "ECV_05"
]

vaping_separate_experiment = [
    "ECVG15",
    "ECV_20",
    "ECVDVSMK",
    "ECV2G05A",
    "ECV2G05B",
    "ECV2G05C",
    "ECV2_10",
    "ECV2_15"
]

print("Vaping variable selected for the main full-population model:")
print(vaping_main_candidates)

print("\nVaping variables reserved for later/specialized analysis:")
print(vaping_separate_experiment)

Vaping variable selected for the main full-population model:
['ECV_05']

Vaping variables reserved for later/specialized analysis:
['ECVG15', 'ECV_20', 'ECVDVSMK', 'ECV2G05A', 'ECV2G05B', 'ECV2G05C', 'ECV2_10', 'ECV2_15']


In [ ]:
# ============================================================
# STAGE 14 — Step 4C
# LBF / MAC / SDC / WTP decisions
# ============================================================

b_main_selected = [
    "ECV_05",
    "SDCDGIMM"
]

b_separate_experiments = {
    "Smoking": ["SMKDVSTY"],
    "Labour_force": ["LBFDGHPW", "LBFDVPFT", "LBFDGWSS"],
    "Main_activity": ["MAC_05"],
    "Social_demographic": ["SDCDVABT", "SDCDVFLA"],
    "Weight_perception": ["WTP_50"]
}

print("B-section variables selected for the main model:")
print(b_main_selected)

print("\nVariables reserved for separate experiments:")
for group, variables in b_separate_experiments.items():
    print(f"{group}: {variables}")

B-section variables selected for the main model:
['ECV_05', 'SDCDGIMM']

Variables reserved for separate experiments:
Smoking: ['SMKDVSTY']
Labour_force: ['LBFDGHPW', 'LBFDVPFT', 'LBFDGWSS']
Main_activity: ['MAC_05']
Social_demographic: ['SDCDVABT', 'SDCDVFLA']
Weight_perception: ['WTP_50']


In [ ]:
# ============================================================
# STAGE 14 — Step 5
# C-section decision
# ============================================================

c_held_out = [
    "RHC_05"
]

print("C-section variables held out:")
print(c_held_out)

C-section variables held out:
['RHC_05']


In [6]:
# ============================================================
# STAGE 14 — Preliminary Documentation- and Domain-Guided Feature Set
# ============================================================

preliminary_features = [
    "ALCDVTTM",
    "DHHDGHSZ",
    "DHHGAGE",
    "DHH_SEX",
    "EDDVH3",
    "FSCDVHF2",
    "GEOGPRV",
    "HWTDGISW",
    "HWTDGWHO",
    "INCDGHH",
    "ECV_05",
    "SDCDGIMM"
]

original_baseline_features = [
    "DHHGAGE",
    "DHH_SEX",
    "GEOGPRV",
    "DHHDGHSZ",
    "EDDVH3",
    "LSM_01",
    "HWTDGISW",
    "WTP_50",
    "SMKDVSTY",
    "FSCDVHF2",
    "INCDGHH"
]

baseline_overlap = [
    feature for feature in preliminary_features
    if feature in original_baseline_features
]

new_features = [
    feature for feature in preliminary_features
    if feature not in original_baseline_features
]

removed_from_baseline = [
    feature for feature in original_baseline_features
    if feature not in preliminary_features
]

print("Preliminary feature count:", len(preliminary_features))
print("Baseline overlap:", len(baseline_overlap))
print("New features:", len(new_features))
print("Baseline features not retained:", len(removed_from_baseline))

print("\nBaseline overlap:")
print(baseline_overlap)

print("\nNew features:")
print(new_features)

print("\nBaseline features not retained:")
print(removed_from_baseline)

Preliminary feature count: 12
Baseline overlap: 8
New features: 4
Baseline features not retained: 3

Baseline overlap:
['DHHDGHSZ', 'DHHGAGE', 'DHH_SEX', 'EDDVH3', 'FSCDVHF2', 'GEOGPRV', 'HWTDGISW', 'INCDGHH']

New features:
['ALCDVTTM', 'HWTDGWHO', 'ECV_05', 'SDCDGIMM']

Baseline features not retained:
['LSM_01', 'WTP_50', 'SMKDVSTY']


## Stage 14 — CCHS Documentation- and Domain-Guided Feature Selection

This stage used the CCHS documentation, variable meaning, applicability, and diabetes-related domain reasoning to construct a preliminary feature set before any model-performance comparison.

### Preliminary feature set

The resulting feature set contains 12 variables:

- `ALCDVTTM` — alcohol-drinking category
- `DHHDGHSZ` — household size
- `DHHGAGE` — age group
- `DHH_SEX` — sex at birth
- `EDDVH3` — highest level of education
- `FSCDVHF2` — household food-security status
- `GEOGPRV` — province/territory of residence
- `HWTDGISW` — adult BMI classification
- `HWTDGWHO` — BMI classification for respondents aged 12–17
- `INCDGHH` — total household income
- `ECV_05` — ever tried an e-cigarette or vaping device
- `SDCDGIMM` — immigrant or non-immigrant status

Eight of these variables were already present in the original 11-feature baseline. Four extend the baseline: `ALCDVTTM`, `HWTDGWHO`, `ECV_05`, and `SDCDGIMM`. Three original baseline variables were not retained in this preliminary representation: `LSM_01`, `WTP_50`, and `SMKDVSTY`. The comparison is verified in the preceding output.

### How the decisions were made

Variables from the A sections were considered first because they provided broadly applicable demographic, socioeconomic, anthropometric, behavioural, and contextual information. Where several variables represented similar information, a more compact representation was preferred. For example, `ALCDVTTM` was used instead of retaining multiple overlapping alcohol measures, and `HWTDGISW` and `HWTDGWHO` were retained together because they represent the adult and 12–17 BMI classifications needed for the full 12+ population.

The B-section review then considered variables that were scientifically plausible but required additional caution because of age restrictions, conditional question paths, overlap, or specialised interpretation.

`ECV_05` was selected as the broadly applicable vaping representation, while the more detailed vaping variables were reserved for later analysis. `SMKDVSTY` was not added to the main 12+ model because its universe is restricted to adults and it will instead be considered in an adult-only smoking experiment. Labour-force and main-activity variables were also reserved for working-age experiments. `WTP_50` was held out because it provides subjective weight perception and may be better evaluated separately against the selected BMI representations.

The three social-demographic variables were treated separately: `SDCDGIMM` was included as the initial contextual representation, while `SDCDVABT` and `SDCDVFLA` were reserved for a later demographic experiment.

`RHC_05` was held out because healthcare-provider use may reflect healthcare access or diagnosis-related processes and therefore represents a different type of information from the main feature set.

### Health-condition and comorbidity decision

Other diagnosed health-condition variables, including high blood pressure, high cholesterol, and cardiovascular conditions, were not automatically added to this preliminary set. They may provide substantial predictive information, but including them changes the information available to the model by incorporating existing health-condition history.

They will therefore be evaluated separately in an expanded health-context experiment after their definitions and applicability have been verified. This allows their incremental contribution to be tested rather than assuming in advance that they belong in the main model.

### Research interpretation

The 12 variables are a **preliminary CCHS documentation- and domain-guided feature set**, not a claim that these are the universally optimal predictors of diabetes.

The selections were made before model performance was evaluated. The purpose of the next modelling stage is therefore to test how this research-guided representation performs relative to the original baseline and, later, to more data-driven feature-selection approaches.

The Core, Review, and Restricted categories used earlier are working research classifications created for this project rather than official Statistics Canada classifications.

# Stage 15

## Stage 15 — Literature-Informed Feature Verification

The preliminary feature set was constructed using CCHS documentation and domain reasoning. The literature review was then used to verify which predictor concepts had stronger support for diabetes classification and whether appropriate CCHS 2022 variables were available to represent them.

For each literature-supported predictor, I verified:

- what the CCHS variable measures;
- who it applies to;
- how its response categories are coded;
- which values represent valid skips or not-stated responses;
- whether it is applicable to the intended modelling population; and
- whether it belongs in the main feature set or a separate experiment.

The purpose of this stage is to connect the literature evidence to the actual CCHS variables rather than assuming that every literature-supported predictor can be used directly in the model.

### Stage 15.1 — BMI / Body-Weight Measures

BMI was identified in the literature review as an important predictor of diabetes classification. The CCHS 2022 PUMF provides three relevant grouped BMI measures:

- `HWTDGISW`: BMI classification for adults aged 18+, based on self-reported height and weight using the international classification.
- `HWTDGWHO`: BMI classification for respondents aged 12–17, based on self-reported height and weight using WHO age- and sex-specific classification.
- `HWTDGBCC`: adjusted BMI classification for adults aged 18+.

The first two variables have different age-specific universes and therefore cannot be treated as interchangeable representations of the same population.

### BMI Feature Decision

For the literature-informed feature set, `HWTDGISW` and `HWTDGWHO` will be retained because together they provide BMI information across the full modelling population aged 12 and older while respecting the CCHS age-specific definitions.

`HWTDGBCC` will be reserved for a controlled experiment comparing the adult self-reported BMI representation with the adjusted adult representation rather than including both in the same feature set.

CCHS special codes will be handled according to the variable documentation. In particular, code 6 represents a population exclusion or valid skip, while code 9 represents a not-stated response. These values will not be treated as ordinary missing observations.

### Stage 15.2 — Hypertension and Other Health-Condition Variables

The literature review identified hypertension and other diagnosed health conditions as important predictor families that were under-represented in the preliminary feature set. Canadian diabetes risk-prediction work, including DPoRT, has used hypertension as a predictor.

The relevant CCHS 2022 variables were then checked for their definitions, universes, response coding, and suitability for controlled modelling experiments.

### Verified Health-Condition Candidates

| Variable | What it measures | Universe | Coding | Preliminary decision |
|---|---|---|---|---|
| `CCC_80` | Has high blood pressure | Respondents with `DOCCC=1` | 1 Yes, 2 No, 9 Not stated | High-priority clinical experiment |
| `CCC_85` | Took medication for high blood pressure in past month | Respondents with `DOCCC=1` | 1 Yes, 2 No, 9 Not stated | Hold; related to `CCC_80` |
| `CCC_90` | Has ever been told by a health professional that blood cholesterol was high | Respondents with `DOCCC=1` | 1 Yes, 2 No, 9 Not stated | Expanded health-context experiment |
| `CCCDGCAR` | Heart disease, heart attack, or effects of stroke | Respondents aged 35+ with `DOCCC=1` | 1 Yes, 2 No, 6 Valid skip, 9 Not stated | Age-restricted secondary experiment |

### Health-Condition Feature Decision

These variables will be treated as a separate clinical information block rather than being added indiscriminately to the main feature set.

`CCC_80` is the highest-priority candidate because hypertension has established support in diabetes prediction literature and the CCHS variable provides a directly defined measure of reported high blood pressure.

`CCC_90` will be evaluated in an expanded clinical-context experiment. It represents whether a health professional has previously told the respondent that their blood cholesterol was high, rather than providing a laboratory measurement.

`CCC_85` will be held out initially because recent antihypertensive medication use is closely related to hypertension status and introduces treatment-related information. Its incremental contribution can be examined after the contribution of `CCC_80` has been established.

`CCCDGCAR` will be reserved for a separate experiment among respondents aged 35 and older because its CCHS universe is age-restricted. Its valid-skip values will not be treated as evidence that a younger respondent does not have cardiovascular disease.

The purpose of these experiments is to test whether clinically reported health information provides incremental predictive value beyond the demographic, anthropometric, socioeconomic, behavioural, and contextual information in the primary feature representation.

### Stage 15.3 — Physical Activity

Physical activity was identified in the literature review as an important predictor of diabetes classification. The CCHS 2022 PUMF contains several derived physical-activity measures, but their applicability must be considered before using them as predictors.

### CCHS Physical-Activity Applicability

The PAA module is identified by the inclusion flag `DOPAA`. In this PUMF, 1,949 respondents have `DOPAA = 1`, while 65,130 have `DOPAA = 0`.

The detailed PAA variables apply to respondents aged 18 and older for whom the module is available. They therefore cannot be used directly in the primary modelling population of respondents aged 12 and older.

These structural skips do not indicate zero physical activity or ordinary missing observations. They reflect the applicability of the module to the respondent.

### Main Physical-Activity Measures Identified

Several derived variables represent related aspects of physical activity:

- `PAADVMVA`: total minutes of moderate-to-vigorous physical activity in the previous 7 days.
- `PAADVACV`: physical-activity indicator based on the Canadian Physical Activity Guidelines.
- `PAADVAC2`: four-level physical-activity classification.
- `PAADVVOL`: weekly physical-activity volume in MET-minutes/week.
- `PAADVWHO`: physical-activity classification based on WHO guidelines.

These measures will not automatically be combined because several represent different transformations of the same underlying activity information.

### Physical-Activity Feature Decision

Physical activity will not be included in the primary all-age 12+ feature set because the PAA module is restricted in both age and availability.

Instead, it will be investigated in a restricted adult PAA experiment using respondents for whom the module is available. The purpose will be to determine whether physical-activity information provides incremental predictive value beyond the established feature set.

`PAADVMVA` will be used as the initial candidate representation because it retains the reported amount of moderate-to-vigorous activity rather than immediately reducing it to a categorical measure. Alternative derived representations can be compared in a later controlled experiment if there is a methodological reason to do so.

This preserves the distinction between scientific relevance and applicability: physical activity may be an important predictor, but its CCHS 2022 availability makes it inappropriate for automatic inclusion in the primary 12+ model.

### Stage 15.4 — Smoking

Smoking was identified in the literature review as a more established diabetes-prediction variable than vaping. The CCHS 2022 PUMF contains several smoking-related measures, but their population applicability and overlap need to be considered before selecting a representation.

### Applicability of `SMKDVSTY`

`SMKDVSTY`, used in the original baseline, represents smoking status for adult respondents. Because its universe is restricted to adults, it cannot be included directly in the primary modelling population of respondents aged 12 and older.

Age-based valid skips should therefore not be interpreted as evidence of non-smoking.

### Smoking Feature Decision

`SMKDVSTY` will be reserved for a separate adult-only smoking experiment. This experiment will test whether smoking information provides incremental predictive value after accounting for the established feature set.

The CCHS smoking section also contains separate measures of current smoking, past smoking, and vaping. These will not be combined indiscriminately. The smoking experiment will begin with a clearly defined smoking-status representation so that any performance change can be attributed to the addition of smoking information rather than a collection of overlapping variables.

The literature review provides stronger support for smoking than for simple ever-vaping status. Therefore, `SMKDVSTY` will be treated as the primary smoking candidate for the adult experiment, while `ECV_05` will remain a secondary or exploratory predictor rather than a core feature.

### Stage 15.5 — Family History and Waist Circumference

The literature review identified family history of diabetes and waist circumference as important predictors used in diabetes prediction models. These predictors were therefore checked against the CCHS 2022 PUMF before being considered for modelling.

The key question was whether the PUMF contains a clearly identifiable variable that represents each predictor and is suitable for the intended modelling population.

### Family History of Diabetes

Family history has strong support in the diabetes prediction literature and is included in established diabetes risk-scoring approaches.

However, an exact family-history-of-diabetes variable could not be sufficiently verified in the CCHS 2022 PUMF documentation reviewed for this project. No variable will therefore be assigned to this predictor without supporting CCHS documentation.

**Decision:** Family history is recorded as a literature-supported predictor that could not be sufficiently verified in the analytical CCHS 2022 PUMF and will not be included in the current feature sets.

### Waist Circumference

Waist circumference is also widely used in diabetes prediction models and represents a different aspect of body composition from BMI.

An appropriate waist-circumference variable could not be sufficiently verified in the CCHS 2022 PUMF documentation reviewed for this project. The available BMI variables will therefore not be treated as substitutes for waist circumference.

**Decision:** Waist circumference is recorded as a literature-supported predictor that could not be sufficiently verified in the analytical CCHS 2022 PUMF and will not be included in the current feature sets.

### Research Limitation

These exclusions reflect dataset availability and variable verification, not a conclusion that the predictors are unimportant.

This distinction is maintained throughout the feature-selection process: literature evidence, CCHS availability, population applicability, and modelling suitability are treated as separate criteria.

### Stage 15.6 — Cholesterol and Cardiovascular Disease

The literature review identified high cholesterol and cardiovascular disease as clinically relevant predictor families. The CCHS 2022 PUMF contains variables representing both concepts, but their exact definitions and population restrictions need to be considered before modelling.

### `CCC_90` — High Cholesterol

`CCC_90` represents whether the respondent has ever been told by a health professional that their blood cholesterol was high.

Its CCHS universe is respondents with `DOCCC = 1`, with the following response codes:

- `1` = Yes
- `2` = No
- `9` = Not stated

This is a reported history of high cholesterol rather than a measured laboratory cholesterol value.

### `CCCDGCAR` — Cardiovascular Condition

`CCCDGCAR` is a grouped cardiovascular-condition variable covering heart disease, previous heart attack, or effects of stroke.

Its universe is restricted to respondents aged 35 and older with `DOCCC = 1`. The response codes are:

- `1` = Yes
- `2` = No
- `6` = Valid skip
- `9` = Not stated

Because of this age restriction, a valid skip cannot be interpreted as evidence that a younger respondent does not have cardiovascular disease.

### Clinical-Context Feature Decision

`CCC_90` will be evaluated in the expanded clinical-context feature set. Its contribution will be interpreted as information from previously reported health-condition history rather than as a laboratory measurement.

`CCCDGCAR` will be evaluated separately among respondents aged 35 and older because its restricted universe makes it unsuitable for the primary all-age model.

The clinical experiments will therefore test whether these health-condition variables provide incremental predictive information beyond the demographic, anthropometric, socioeconomic, behavioural, and contextual features in the primary representation. Because the CCHS 2022 data are cross-sectional, the modelling results will not establish a temporal or causal relationship between these conditions and diabetes status.

## 15.7 — Social-Demographic Representation

The literature review identified immigration- and identity-related characteristics as potentially relevant predictors in diabetes classification and risk models. These concepts are not interchangeable, so the corresponding CCHS variables were examined separately.

### 15.7.1 Relevant CCHS 2022 Variables

The CCHS 2022 PUMF contains:

- `SDCDGIMM`: immigrant flag
- `SDCDVABT`: Indigenous identity
- `SDCDVFLA`: visible minority flag

`SDCDGIMM` distinguishes non-immigrant respondents from immigrant or non-permanent resident categories.

`SDCDVABT` identifies respondents reporting Indigenous identity, including First Nations, Métis, or Inuk/Inuit identity.

`SDCDVFLA` identifies respondents classified as a visible minority.

These variables represent different social-demographic characteristics and are therefore not treated as interchangeable predictors.

### 15.7.2 Feature Decision

The three variables will not be added together automatically to the main feature set.

`SDCDGIMM` will be retained as the initial candidate for the literature-informed feature representation because it provides a broad, clearly defined migration-status measure.

`SDCDVABT` and `SDCDVFLA` will be evaluated separately in an expanded demographic experiment. Their contribution will be assessed in terms of incremental predictive value, interpretation, and implications for generalizability rather than assuming that their inclusion will improve classification.

## 15.8 — Audit of the Preliminary 12-Feature Set

The preliminary 12-feature set was constructed before the external literature review using CCHS documentation, population applicability, redundancy considerations, and domain reasoning.

The literature review provided a second basis for evaluating these variables. Each feature was therefore reconsidered according to:

- strength of evidence in diabetes prediction literature;
- applicability to the CCHS 2022 modelling population;
- conceptual relationship to diabetes status;
- whether it provides core or contextual information; and
- whether its contribution should be tested incrementally.

This audit does not assume that every variable in the preliminary set belongs in the final core. Instead, variables are retained, moved to secondary experiments, or reconsidered according to the evidence and their role in the experimental design.

### 15.8.1 Reclassification of the Preliminary Features

| Variable | Concept | Current decision |
|---|---|---|
| `DHHGAGE` | Age group | Strong keep |
| `HWTDGISW` / `HWTDGWHO` | BMI classification | Strong keep |
| `DHH_SEX` | Sex at birth | Keep |
| `EDDVH3` | Household education | Keep |
| `INCDGHH` | Household income | Keep; test incremental value |
| `SDCDGIMM` | Immigrant status | Contextual candidate |
| `GEOGPRV` | Province/territory | Geographic/contextual candidate |
| `FSCDVHF2` | Household food security | Secondary/contextual experiment |
| `ALCDVTTM` | Type of drinker | Secondary experiment |
| `DHHDGHSZ` | Household size | Reconsider; not part of the core |
| `ECV_05` | Ever tried e-cigarette/vaping | Secondary/exploratory |

### 15.8.2 Interpretation of the Reclassification

The reclassification does not mean that contextual or weaker predictors are irrelevant.

Variables such as income, food security, immigrant status, and province/territory may provide useful contextual information, but their contribution should be evaluated separately from more consistently established predictors such as age and BMI.

Similarly, household size, alcohol use, and ever-vaping may still be scientifically interesting, but there is less reason to treat them as core predictors without testing their incremental contribution.

The feature sets therefore distinguish between:

- core predictors;
- contextual predictors; and
- secondary or exploratory predictors.

### 15.8.3 Direction for the Next Feature Sets

The literature-informed experiments will use the following working structure.

**Core predictors**

- age
- BMI
- sex
- education

**Contextual predictors**

- income
- immigrant status
- province/territory
- food security

**Secondary or exploratory predictors**

- alcohol
- household size
- ever-vaping
- other weaker behavioural or contextual variables

Hypertension, high cholesterol, cardiovascular disease, smoking, and physical activity will be evaluated separately through controlled experiments because they either introduce a different type of health information or have population-applicability constraints.

The final feature sets will be frozen after these controlled experimental decisions have been documented.

## 15.9 — Feature-Set Freeze and Experimental Structure

The preceding stages showed that candidate variables differ in scientific evidence, CCHS applicability, information type, and population coverage.

Rather than repeatedly modifying one feature set, the modelling stage will use clearly defined feature conditions. This allows the experiments to answer specific questions about the contribution of different information blocks.

The main comparisons are:

- the original baseline;
- the preliminary documentation/domain-guided set;
- the literature-informed core;
- incremental clinical information;
- restricted behavioural information; and
- automatic feature selection.

### 15.9.1 Main Experimental Feature Sets

#### A — Original Baseline

The original baseline is preserved exactly as implemented in the earlier modelling notebook:

`DHHGAGE`, `DHH_SEX`, `GEOGPRV`, `DHHDGHSZ`, `EDDVH3`, `LSM_01`,  
`HWTDGISW`, `WTP_50`, `SMKDVSTY`, `FSCDVHF2`, `INCDGHH`

This acts as the historical reference condition.

### 15.9.2 B — Preliminary Documentation/Domain-Guided Set

This 12-feature set was constructed before the external literature review:

`ALCDVTTM`, `DHHDGHSZ`, `DHHGAGE`, `DHH_SEX`, `EDDVH3`,  
`FSCDVHF2`, `GEOGPRV`, `HWTDGISW`, `HWTDGWHO`, `INCDGHH`,  
`ECV_05`, `SDCDGIMM`

It is retained as an intermediate research condition rather than treated as the final feature set.

### 15.9.3 C — Literature-Informed Core

The literature audit shifted priority toward variables with stronger and more consistent support while retaining variables that are broadly applicable to the CCHS 2022 modelling population.

The current literature-informed core is:

`DHHGAGE`, `DHH_SEX`, `EDDVH3`, `HWTDGISW`, `HWTDGWHO`,  
`INCDGHH`, `SDCDGIMM`, `GEOGPRV`

This is a working core for the main broadly applicable population. Clinical variables and restricted behavioural modules are evaluated separately.

### 15.9.4 D — Clinical Expansion Experiments

The clinical information block will be evaluated incrementally.

**D1 — Core + hypertension**

Add `CCC_80`.

**D2 — Core + hypertension + high cholesterol**

Add `CCC_80` and `CCC_90`.

**D3 — 35+ clinical-history experiment**

Among respondents aged 35 and older, evaluate the applicable core features together with `CCC_80`, `CCC_90`, and `CCCDGCAR`.

The D3 experiment will use the feature representation applicable to the 35+ population rather than carrying age-specific 12–17 variables into the restricted analysis.

The purpose of these experiments is to determine whether reported clinical health-condition information provides incremental predictive value beyond the broadly applicable feature representation.

### 15.9.5 E — Restricted Behavioural Experiments

Some scientifically relevant behavioural predictors cannot be inserted directly into the primary 12+ model because their CCHS universes are restricted.

**E1 — Adult smoking experiment**

Evaluate a clearly defined smoking-status representation among eligible adult respondents, using `SMKDVSTY` as the initial candidate.

**E2 — Restricted adult physical-activity experiment**

Evaluate an appropriate physical-activity representation among adult respondents for whom the PAA module is available.

These experiments are kept separate from the primary 12+ condition so that their population restrictions are handled explicitly.

### 15.9.6 F — Automatic Feature Selection

An automatic feature-selection experiment will be performed using the broader candidate pool established during the dataset investigation.

The candidate pool will first be restricted to variables whose applicability is compatible with the selected modelling population. Variables with incompatible or restricted universes will not be forced into the full-population experiment simply because they are present in the broader PUMF.

The first automatic-selection approach will use L1-regularized logistic regression.

Feature selection will be performed using training data only. Validation data will be used for model-selection decisions, while the final test set will remain untouched until final evaluation.

### 15.9.7 Experimental Conditions Summary

| Condition | Purpose |
|---|---|
| A | Historical baseline |
| B | Preliminary documentation/domain-guided feature set |
| C | Literature-informed broadly applicable core |
| D1 | Incremental effect of hypertension |
| D2 | Incremental effect of hypertension + high cholesterol |
| D3 | Expanded 35+ cardiovascular/clinical-history experiment |
| E1 | Adult smoking experiment |
| E2 | Restricted adult physical-activity experiment |
| F | Automatic feature-selection experiment |

The conditions are designed to isolate the contribution of different feature blocks rather than simply maximize the number of predictors.

## 15.10 — Modelling Protocol

The modelling stage will use a consistent protocol so that differences between experiments can be attributed primarily to the feature condition and model rather than changes in preprocessing or evaluation.

For each experiment:

1. select a frozen feature condition;
2. define the corresponding eligible modelling population;
3. exclude unusable target responses;
4. create a fixed stratified train/validation/test split;
5. fit preprocessing using the training data only;
6. fit the model using the training data;
7. use the validation set for model-selection and threshold decisions;
8. lock the selected configuration and threshold;
9. evaluate the final model once on the untouched test set; and
10. record performance, interpretation, and failure cases.

The test set will not be used for feature selection, hyperparameter tuning, or threshold selection.

### 15.10.1 Data Splitting

For experiments using the same modelling population, the same fixed stratified split will be retained so that feature-set and model comparisons are made on the same observations.

Population-restricted experiments, such as the 35+ clinical experiment and restricted adult behavioural experiments, will use a fixed stratified split generated within their eligible population.

The training set is used to learn model parameters and preprocessing parameters.

The validation set is used for model-selection decisions, threshold selection, and other predefined modelling choices.

The final test set is reserved for locked evaluation.

### 15.10.2 Preprocessing

All preprocessing operations must be fitted using the training data only.

Categorical variables will be encoded using an appropriate categorical encoding strategy, while numerical variables will be processed according to their data type and missing-value structure.

The fitted preprocessing pipeline will then be applied unchanged to the validation and test sets.

CCHS-specific special codes will be interpreted using variable-specific documentation rather than a global missing-value rule.

### 15.10.3 Class Imbalance

Diabetes is the minority target class.

Where appropriate, class-weighted training will be used to increase the influence of minority-class observations during model fitting. The class-weighting strategy will be recorded for each experiment.

Performance will not be evaluated using accuracy alone because accuracy can be misleading when the target classes are imbalanced.

### 15.10.4 Models

The primary models will be:

1. Logistic Regression
2. Random Forest
3. Gradient Boosting

These models provide complementary modelling perspectives:

- Logistic Regression provides an interpretable linear reference model.
- Random Forest provides a nonlinear ensemble model.
- Gradient Boosting provides a second nonlinear ensemble approach.

Additional algorithms will not be added solely to increase the number of models. Any additional model must have a methodological reason for inclusion.

### 15.10.5 Evaluation Metrics

Each experiment will report:

- Accuracy
- Precision
- Recall
- F1-score
- ROC-AUC
- PR-AUC
- Confusion matrix

ROC-AUC will be used to assess threshold-independent discrimination.

PR-AUC will receive particular attention because the diabetes class is relatively uncommon.

Threshold-dependent metrics will be reported using the classification threshold selected from the validation set.

### 15.10.6 Threshold Selection

The default probability threshold of 0.50 will not automatically be assumed to be optimal.

For each model, the classification threshold will be selected on the validation set using a predefined evaluation rule.

Once selected, the threshold will be locked before final test evaluation.

The test set will not be examined when choosing the threshold.

### 15.10.7 Failure Analysis

For each final model, both successful and unsuccessful predictions will be examined.

Particular attention will be given to:

- false positives;
- false negatives;
- differences between training and validation/test performance;
- cases where different models disagree; and
- feature patterns associated with difficult cases.

Failure analysis will be used to understand why a model succeeds or fails rather than reporting performance metrics without interpretation.

### 15.10.8 Interpretation

Interpretation will depend on the model type.

For Logistic Regression, coefficient patterns will be examined within the one-hot encoded feature representation.

For tree-based models, feature importance or permutation importance may be used to examine which features contribute most strongly to predictions.

These measures will be interpreted as model-specific predictive information rather than causal evidence.

### 15.10.9 Survey Weight Limitation

The CCHS sampling weight `WTS_M` will not be treated as an ordinary predictor.

The primary machine-learning results therefore represent respondent-level predictive modelling rather than survey-weighted population estimates.

Any future weighted analysis will be treated as a separate sensitivity analysis with its own methodology.

### 15.10.10 Experiment Record

Each experiment will record:

- feature set;
- modelling population;
- model;
- preprocessing;
- class-weighting strategy;
- model configuration;
- threshold-selection rule;
- selected threshold;
- training performance;
- validation performance;
- final test performance;
- confusion matrix;
- feature interpretation;
- failure cases; and
- limitations.

This record will make it possible to explain what was tested, what changed between conditions, what improved or failed, and why the observed result changed.